// English Grammar - Exercise Bank
// Mỗi câu hỏi gắn với: component (chủ điểm trong Atlas), topic (nhãn hiển thị),
// level (CEFR) để hệ thống lọc theo trình độ và mở bài luyện riêng cho từng chủ điểm.
// Quy tắc biên soạn: mỗi câu chỉ có DUY NHẤT một đáp án đúng; các phương án nhiễu
// phải sai rõ ràng về ngữ pháp (không dùng biến thể Anh–Mỹ hay từ đồng nghĩa hợp lệ).

const grammarExerciseBank = (function () {
    let seq = 0;
    const q = (component, topic, level, question, options, correct, explanation) => ({
        id: `q${++seq}`,
        component,
        topic,
        level,
        question,
        options,
        correct,
        explanation
    });

    return [
        // ==================== TRẬT TỰ CÂU & TỪ LOẠI ====================
        q('sentence-order', 'Trật tự câu', 'A1', 'Chọn câu đúng trật tự:', ['She reads books every day.', 'She every day reads books.', 'Reads she books every day.', 'Books every day she reads.'], 0, 'Câu trần thuật: Subject + Verb + Object + Time. Trạng ngữ thời gian đứng cuối.'),
        q('sentence-order', 'Trật tự câu', 'A1', 'Sắp xếp: "rice / they / eat"', ['They eat rice.', 'They rice eat.', 'Eat they rice.', 'Rice they eat.'], 0, 'S + V + O là trật tự mặc định của câu tiếng Anh.'),
        q('sentence-order', 'Trật tự câu', 'A1', 'Câu nào đặt trạng từ tần suất đúng vị trí?', ['She always arrives early.', 'She arrives always early.', 'Always she arrives early.', 'She arrives early always.'], 0, 'Trạng từ tần suất (always, often, never) đứng TRƯỚC động từ thường.'),
        q('sentence-order', 'Trật tự câu', 'A2', 'Câu nào đặt trạng từ tần suất đúng khi có động từ "be"?', ['He is never late.', 'He never is late.', 'Never he is late.', 'He is late never.'], 0, 'Với động từ "be", trạng từ tần suất đứng SAU be: "is never late".'),
        q('sentence-order', 'Trật tự câu', 'A2', 'Chọn trật tự đúng của trạng ngữ:', ['I studied at the library yesterday.', 'I studied yesterday at the library.', 'I yesterday studied at the library.', 'At the library I yesterday studied.'], 0, 'Trật tự quen thuộc: Manner → Place → Time. Nơi chốn đứng trước thời gian.'),
        q('sentence-order', 'Trật tự câu', 'B1', 'Câu nào có trật tự tân ngữ đúng?', ['They gave me a gift.', 'They gave a gift me.', 'They gave to me a gift.', 'They me gave a gift.'], 0, 'S + V + tân ngữ gián tiếp (me) + tân ngữ trực tiếp (a gift), không cần "to".'),

        q('parts-of-speech', 'Từ loại', 'A1', '"quickly" thuộc từ loại nào?', ['adverb', 'noun', 'verb', 'adjective'], 0, 'Hậu tố "-ly" gắn vào tính từ tạo ra trạng từ: quick → quickly.'),
        q('parts-of-speech', 'Từ loại', 'A2', '"happiness" thuộc từ loại nào?', ['noun', 'verb', 'adjective', 'adverb'], 0, 'Hậu tố "-ness" biến tính từ thành danh từ: happy → happiness.'),
        q('parts-of-speech', 'Từ loại', 'A2', 'Trong "She sings beautifully", từ "beautifully" bổ nghĩa cho từ nào?', ['sings', 'She', 'cả câu', 'beautiful'], 0, 'Trạng từ bổ nghĩa cho động từ, cho biết hành động diễn ra thế nào.'),
        q('parts-of-speech', 'Từ loại', 'B1', 'Trong "The water is running", "running" đóng vai trò gì?', ['một phần của động từ (present participle)', 'danh từ', 'tính từ', 'trạng từ'], 0, 'be + V-ing tạo thành thì tiếp diễn, nên "running" là phần động từ chính.'),
        q('parts-of-speech', 'Từ loại', 'B1', 'Trong "Running is good for you", "Running" đóng vai trò gì?', ['danh động từ làm chủ ngữ', 'động từ chính', 'tính từ', 'trạng từ'], 0, 'V-ing đứng ở vị trí chủ ngữ là gerund, hoạt động như một danh từ.'),
        q('word-formation', 'Cấu tạo từ', 'B1', 'She gave a very ___ speech. (impress)', ['impressive', 'impression', 'impressively', 'impressed'], 0, 'Cần một tính từ đứng trước danh từ "speech" → impressive.'),
        q('word-formation', 'Cấu tạo từ', 'B1', 'His ___ to the team was huge. (contribute)', ['contribution', 'contribute', 'contributive', 'contributing'], 0, 'Sau tính từ sở hữu "His" cần một danh từ → contribution.'),
        q('word-formation', 'Cấu tạo từ', 'B2', 'The instructions were written very ___. (clear)', ['clearly', 'clear', 'clarity', 'clearness'], 0, 'Bổ nghĩa cho động từ "were written" cần trạng từ → clearly.'),
        q('word-formation', 'Cấu tạo từ', 'B2', 'It is ___ to park here. (legal)', ['illegal', 'unlegal', 'dislegal', 'nonlegal'], 0, 'Tiền tố phủ định của "legal" là "il-" (đứng trước l): illegal.'),
        q('word-formation', 'Cấu tạo từ', 'B2', 'He behaved very ___. (responsible)', ['responsibly', 'responsibility', 'responsibleness', 'responsible'], 0, 'Tính từ kết thúc bằng "-ble" đổi thành trạng từ "-bly": responsible → responsibly.'),
        q('word-formation', 'Cấu tạo từ', 'B2', 'The machine is not working. It needs to be ___. (place)', ['replaced', 'displaced', 'misplaced', 'unplaced'], 0, 'Tiền tố "re-" = làm lại/thay thế: replace = thay mới.'),

        // ==================== DANH TỪ, MẠO TỪ, LƯỢNG TỪ ====================
        q('nouns-plurals', 'Danh từ số nhiều', 'A1', 'Số nhiều của "child" là:', ['children', 'childs', 'childes', 'childrens'], 0, '"Child" là danh từ bất quy tắc: child → children.'),
        q('nouns-plurals', 'Danh từ số nhiều', 'A1', 'Số nhiều của "box" là:', ['boxes', 'boxs', 'boxies', 'box'], 0, 'Danh từ tận cùng -x, -s, -ch, -sh, -o thêm "-es".'),
        q('nouns-plurals', 'Danh từ số nhiều', 'A2', 'Số nhiều của "city" là:', ['cities', 'citys', 'cityes', 'citis'], 0, 'Phụ âm + y → đổi y thành i rồi thêm -es: city → cities.'),
        q('nouns-plurals', 'Danh từ số nhiều', 'A2', 'Số nhiều của "leaf" là:', ['leaves', 'leafs', 'leafes', 'leave'], 0, 'Nhiều danh từ tận cùng -f/-fe đổi thành -ves: leaf → leaves.'),
        q('nouns-plurals', 'Danh từ số nhiều', 'B1', 'Câu nào đúng?', ['These data are inconclusive.', 'These data is inconclusive.', 'This data are inconclusive.', 'These datas are inconclusive.'], 0, 'Trong văn phong học thuật, "data" là số nhiều của "datum" nên đi với "are".'),
        q('nouns-plurals', 'Danh từ số nhiều', 'B1', 'Số nhiều của "phenomenon" là:', ['phenomena', 'phenomenons', 'phenomenones', 'phenomenae'], 0, 'Danh từ gốc Hy Lạp: -on → -a (phenomenon → phenomena).'),

        q('articles-determiners', 'Mạo từ', 'A1', 'I need ___ apple.', ['an', 'a', 'the', 'this'], 0, '"apple" bắt đầu bằng âm nguyên âm /æ/ → dùng "an".'),
        q('articles-determiners', 'Mạo từ', 'A1', 'I want to buy ___ new computer.', ['a', 'an', 'the', 'some'], 0, '"new" bắt đầu bằng âm phụ âm /n/ → dùng "a".'),
        q('articles-determiners', 'Mạo từ', 'A1', '___ sun is very bright today.', ['The', 'A', 'An', 'Some'], 0, 'Vật thể duy nhất trên đời (mặt trời, mặt trăng) luôn đi với "the".'),
        q('articles-determiners', 'Mạo từ', 'A2', 'She is ___ honest student.', ['an', 'a', 'the', 'some'], 0, '"honest" có h câm, phát âm bắt đầu bằng nguyên âm /ɒ/ → dùng "an". Chọn a/an theo ÂM, không theo chữ cái.'),
        q('articles-determiners', 'Mạo từ', 'A2', 'He studies at ___ university in Hue.', ['a', 'an', 'the', 'some'], 0, '"university" phát âm /juː-/ bắt đầu bằng âm phụ âm /j/ → dùng "a".'),
        q('articles-determiners', 'Mạo từ', 'A2', 'I bought a shirt. ___ shirt was expensive.', ['The', 'A', 'An', 'Some'], 0, 'Lần đầu nhắc dùng a/an, lần sau khi người nghe đã biết thì dùng "the".'),
        q('articles-determiners', 'Mạo từ', 'B1', '___ Alps are in Europe.', ['The', 'A', 'An', 'Some'], 0, 'Dãy núi, quần đảo, tên sông và tên nước số nhiều đi với "the".'),
        q('articles-determiners', 'Mạo từ', 'B1', 'She plays ___ piano every evening.', ['the', 'a', 'an', 'Ø (không mạo từ)'], 0, 'Nhạc cụ đi với "the": play the piano, play the guitar.'),
        q('articles-determiners', 'Mạo từ (zero article)', 'A2', '___ students must study hard. (nói về sinh viên nói chung)', ['Ø (không mạo từ)', 'The', 'A', 'An'], 0, 'Danh từ số nhiều mang nghĩa chung chung thì không dùng mạo từ.'),
        q('articles-determiners', 'Mạo từ (zero article)', 'A2', 'I like ___ music. (nói về âm nhạc nói chung)', ['Ø (không mạo từ)', 'the', 'a', 'an'], 0, 'Danh từ không đếm được mang nghĩa chung chung không dùng mạo từ.'),
        q('articles-determiners', 'Mạo từ (zero article)', 'B1', 'He goes to ___ school by bike. (đi học)', ['Ø (không mạo từ)', 'the', 'a', 'an'], 0, 'go to school/church/bed/prison với nghĩa mục đích thì bỏ mạo từ.'),
        q('articles-determiners', 'Mạo từ (zero article)', 'B1', 'We had ___ lunch at noon.', ['Ø (không mạo từ)', 'the', 'a', 'an'], 0, 'Tên bữa ăn (breakfast, lunch, dinner) không dùng mạo từ khi nói chung.'),

        q('countable-uncountable', 'Đếm được / không đếm được', 'A1', 'Can I have ___ water, please?', ['some', 'a', 'an', 'many'], 0, '"water" không đếm được nên không dùng a/an; "some" là lựa chọn tự nhiên.'),
        q('countable-uncountable', 'Đếm được / không đếm được', 'A2', 'How ___ advice can you give me?', ['much', 'many', 'few', 'a few'], 0, '"advice" không đếm được → dùng "much" khi hỏi số lượng.'),
        q('countable-uncountable', 'Đếm được / không đếm được', 'A2', 'I need ___ information about this course.', ['some', 'a', 'an', 'many'], 0, '"information" không đếm được, không có dạng số nhiều "informations".'),
        q('countable-uncountable', 'Đếm được / không đếm được', 'B1', 'Cách đếm danh từ không đếm được – chọn câu đúng:', ['She gave me two pieces of advice.', 'She gave me two advices.', 'She gave me two advice.', 'She gave me a advice.'], 0, 'Muốn đếm danh từ không đếm được phải dùng đơn vị: a piece of advice.'),
        q('countable-uncountable', 'Đếm được / không đếm được', 'B1', 'Từ nào KHÔNG đếm được?', ['furniture', 'chair', 'table', 'lamp'], 0, '"furniture" là danh từ tập hợp không đếm được; các món cụ thể thì đếm được.'),
        q('countable-uncountable', 'Đếm được / không đếm được', 'B2', 'Trong "I had a strange experience", "experience" mang nghĩa gì?', ['một trải nghiệm cụ thể (đếm được)', 'kinh nghiệm nói chung', 'lời khuyên', 'thông tin'], 0, 'Một số danh từ đổi nghĩa theo tính đếm được: experience = trải nghiệm (đếm được) / kinh nghiệm (không đếm được).'),

        q('quantifiers', 'Lượng từ', 'A2', 'How ___ people are there in your family?', ['many', 'much', 'little', 'a little'], 0, '"people" là danh từ đếm được số nhiều → dùng "many".'),
        q('quantifiers', 'Lượng từ', 'A2', 'There are ___ students in the class, about five or six.', ['a few', 'a little', 'much', 'little'], 0, '"a few" + danh từ đếm được số nhiều, mang nghĩa tích cực "một vài".'),
        q('quantifiers', 'Lượng từ', 'B1', 'Hurry up! We have ___ time left – only ten minutes.', ['little', 'a little', 'few', 'a few'], 0, '"little" (không có a) mang nghĩa tiêu cực: rất ít, gần như không đủ.'),
        q('quantifiers', 'Lượng từ', 'B1', 'Don\'t worry, there is still ___ hope.', ['a little', 'little', 'a few', 'few'], 0, '"a little" mang sắc thái tích cực: vẫn còn một chút.'),
        q('quantifiers', 'Lượng từ', 'B1', '___ of the students has his own locker.', ['Each', 'All', 'Both', 'Several'], 0, '"Each of + danh từ số nhiều" luôn đi với động từ số ít: has.'),
        q('quantifiers', 'Lượng từ', 'B1', 'I have ___ money, so I can\'t buy it.', ['hardly any', 'hardly no', 'not any hardly', 'hardly some'], 0, '"hardly any" = gần như không có. Không dùng "hardly" với "no" (phủ định kép).'),
        q('quantifiers', 'Lượng từ', 'B2', '___ the two answers is correct.', ['Neither of', 'None of', 'Either of them are', 'Both of'], 0, 'Nói về HAI đối tượng và cả hai đều không đúng → "Neither of" + động từ số ít.'),
        q('quantifiers', 'Lượng từ', 'B2', 'She has ___ friends that she never feels lonely.', ['so many', 'so much', 'such many', 'too many'], 0, 'so + many + danh từ đếm được + that: cấu trúc chỉ mức độ dẫn tới kết quả.'),

        // ==================== ĐẠI TỪ, TÍNH TỪ, TRẠNG TỪ, SO SÁNH ====================
        q('pronouns-possessives', 'Đại từ', 'A1', 'She told ___ that she would come.', ['me', 'I', 'my', 'mine'], 0, 'Sau động từ cần đại từ tân ngữ: me, you, him, her, us, them.'),
        q('pronouns-possessives', 'Đại từ', 'A2', 'This book is ___. I bought it yesterday.', ['mine', 'my', 'me', 'myself'], 0, 'Đại từ sở hữu đứng một mình, không kèm danh từ: mine, yours, hers, ours.'),
        q('pronouns-possessives', 'Đại từ', 'A2', 'Tom and ___ went to the cinema.', ['I', 'me', 'my', 'mine'], 0, 'Chủ ngữ của câu cần đại từ chủ ngữ "I": Tom and I went...'),
        q('pronouns-possessives', 'Đại từ', 'B1', 'She hurt ___ while she was cooking.', ['herself', 'her', 'hers', 'she'], 0, 'Khi chủ ngữ và tân ngữ cùng là một người, dùng đại từ phản thân: herself.'),
        q('pronouns-possessives', 'Đại từ', 'B1', 'They helped ___ with the homework. (giúp lẫn nhau)', ['each other', 'themselves', 'them', 'theirs'], 0, '"each other" = lẫn nhau; "themselves" = tự làm cho chính họ.'),
        q('pronouns-possessives', 'Đại từ', 'B2', 'Everyone should bring ___ own laptop.', ['their', 'his', 'its', 'them'], 0, 'Tiếng Anh hiện đại dùng "their" trung tính sau everyone/somebody.'),
        q('dummy-it', 'It & There', 'A2', '___ is a good restaurant near my house.', ['There', 'It', 'That', 'This'], 0, 'Giới thiệu sự tồn tại của một vật → There is / There are.'),
        q('dummy-it', 'It & There', 'A2', '___ is very cold today.', ['It', 'There', 'That', 'This'], 0, 'Nói về thời tiết, thời gian, khoảng cách → chủ ngữ giả "It".'),
        q('dummy-it', 'It & There', 'B1', '___ is no point in arguing with him.', ['There', 'It', 'That', 'This'], 0, 'Cấu trúc cố định: There is no point in + V-ing.'),

        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'A2', 'She speaks English ___.', ['well', 'good', 'best', 'goodly'], 0, 'Bổ nghĩa cho động từ "speaks" cần trạng từ. Trạng từ của "good" là "well".'),
        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'A2', 'The soup tastes ___.', ['delicious', 'deliciously', 'more delicious', 'deliciousness'], 0, 'Động từ giác quan (taste, look, smell, sound, feel) đi với TÍNH TỪ, không phải trạng từ.'),
        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'B1', 'He drives ___ than his brother.', ['more carefully', 'more careful', 'carefuller', 'most carefully'], 0, 'So sánh hơn của trạng từ dài: more + adverb + than.'),
        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'B1', 'She was ___ tired to finish the race.', ['too', 'so', 'very', 'enough'], 0, 'too + adj + to V = quá... nên không thể...'),
        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'B1', 'He isn\'t old ___ to drive.', ['enough', 'too', 'so', 'very'], 0, 'enough đứng SAU tính từ: old enough to V.'),
        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'B2', 'The film was ___. I fell asleep.', ['boring', 'bored', 'boredom', 'more bored'], 0, '-ing mô tả tính chất của sự vật; -ed mô tả cảm xúc của người.'),
        q('adjectives-adverbs', 'Tính từ & Trạng từ', 'B2', 'I was ___ with the result.', ['disappointed', 'disappointing', 'disappoint', 'disappointment'], 0, 'Người cảm thấy thế nào → dùng phân từ "-ed": disappointed.'),
        q('adjective-order', 'Trật tự tính từ', 'B1', 'Trật tự tính từ (chiếc bàn) – chọn phương án đúng:', ['a beautiful small old Italian table', 'a small beautiful Italian old table', 'an Italian old small beautiful table', 'a small old beautiful Italian table'], 0, 'Trật tự: Opinion → Size → Age → Shape → Colour → Origin → Material.'),
        q('adjective-order', 'Trật tự tính từ', 'B1', 'Trật tự tính từ (áo khoác) – chọn phương án đúng:', ['a nice long black leather coat', 'a black long nice leather coat', 'a leather black long nice coat', 'a long nice black leather coat'], 0, 'Opinion (nice) → Size (long) → Colour (black) → Material (leather).'),

        q('comparisons', 'So sánh', 'A2', 'She is ___ than her sister.', ['taller', 'tall', 'tallest', 'more tall'], 0, 'Tính từ ngắn một âm tiết: thêm "-er" + than.'),
        q('comparisons', 'So sánh', 'A2', 'This book is ___ than that one.', ['more interesting', 'interestinger', 'most interesting', 'interesting'], 0, 'Tính từ dài (3 âm tiết trở lên): more + adj + than.'),
        q('comparisons', 'So sánh', 'A2', 'This is the ___ movie I have ever seen.', ['best', 'better', 'good', 'goodest'], 0, 'So sánh nhất bất quy tắc: good → better → best (hay nhất).'),
        q('comparisons', 'So sánh', 'B1', 'My new phone is ___ expensive as my old one.', ['as', 'so', 'more', 'than'], 0, 'So sánh bằng: as + adj + as.'),
        q('comparisons', 'So sánh', 'B1', 'He doesn\'t run ___ fast as I do.', ['as', 'more', 'than', 'the'], 0, 'So sánh bằng ở dạng phủ định vẫn giữ "as ... as".'),
        q('comparisons', 'So sánh', 'B1', 'Nhấn mạnh so sánh hơn – chọn câu đúng:', ['This road is far busier than that one.', 'This road is very busier than that one.', 'This road is too busier than that one.', 'This road is so busier than that one.'], 0, 'Nhấn mạnh so sánh hơn dùng far/much/a lot, KHÔNG dùng very.'),
        q('comparisons', 'So sánh', 'B2', '___ he studied, ___ he understood.', ['The more / the more', 'More / more', 'The most / the most', 'As more / as more'], 0, 'So sánh kép: The + comparative..., the + comparative...'),
        q('comparisons', 'So sánh', 'B2', 'Prices are getting ___.', ['higher and higher', 'more and more high', 'high and high', 'the higher and higher'], 0, 'Diễn tả xu hướng tăng dần: comparative + and + comparative.'),

        // ==================== GIỚI TỪ ====================
        q('prepositions', 'Giới từ', 'A1', 'She arrived ___ Monday morning.', ['on', 'in', 'at', 'by'], 0, 'Thứ và ngày cụ thể dùng "on"; kể cả khi có "morning" đi kèm ngày.'),
        q('prepositions', 'Giới từ', 'A1', 'I live ___ Hanoi.', ['in', 'on', 'at', 'to'], 0, 'Thành phố, quốc gia, không gian lớn → "in".'),
        q('prepositions', 'Giới từ', 'A1', 'The meeting is ___ 3 p.m.', ['at', 'in', 'on', 'by'], 0, 'Giờ chính xác → "at". (at 3 p.m., at noon, at midnight)'),
        q('prepositions', 'Giới từ', 'A2', 'The book is ___ the table.', ['on', 'in', 'at', 'to'], 0, 'Tiếp xúc bề mặt → "on".'),
        q('prepositions', 'Giới từ', 'A2', 'I go to school ___ bus.', ['by', 'in', 'on', 'at'], 0, 'Phương tiện chung chung: by bus, by train, by car (không có mạo từ).'),
        q('prepositions', 'Giới từ', 'A2', 'She was born ___ 2000.', ['in', 'on', 'at', 'by'], 0, 'Năm, tháng, mùa, thế kỷ → "in".'),
        q('prepositions', 'Giới từ', 'B1', 'Please finish the report ___ Friday. (hạn chót)', ['by', 'until', 'in', 'on'], 0, '"by" = không muộn hơn (hạn chót); "until" = kéo dài liên tục tới lúc đó.'),
        q('prepositions', 'Giới từ', 'B1', 'I waited ___ 6 o\'clock, then I left.', ['until', 'by', 'in', 'since'], 0, '"until" nhấn hành động kéo dài liên tục cho tới mốc thời gian.'),
        q('prepositions', 'Giới từ', 'B1', 'We got ___ the bus at the last stop.', ['off', 'out of', 'down from', 'from'], 0, 'Xuống xe buýt/tàu/máy bay: get off. (Ra khỏi ô tô con mới là get out of.)'),
        q('prepositions', 'Giới từ', 'B1', 'The plane arrived ___ Noi Bai Airport.', ['at', 'to', 'in', 'on'], 0, 'arrive at + địa điểm nhỏ (sân bay, nhà ga); arrive in + thành phố, quốc gia. Không bao giờ "arrive to".'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B1', 'She is interested ___ learning English.', ['in', 'on', 'at', 'to'], 0, 'Collocation cố định: be interested IN + V-ing.'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B1', 'She is good ___ mathematics.', ['at', 'in', 'on', 'with'], 0, 'Collocation cố định: be good AT something (giỏi về cái gì).'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B1', 'I am tired ___ working late every night.', ['of', 'from', 'with', 'at'], 0, 'be tired OF = chán ngán. (be tired FROM = mệt vì, nghĩa khác.)'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B2', 'This result depends ___ several factors.', ['on', 'of', 'from', 'to'], 0, 'Collocation cố định: depend ON.'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B2', 'He apologised ___ being late.', ['for', 'of', 'about', 'to'], 0, 'apologise TO somebody FOR something.'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B2', 'Vietnam is famous ___ its street food.', ['for', 'of', 'about', 'with'], 0, 'be famous FOR + điều làm nên tên tuổi.'),
        q('prepositional-phrases', 'Cụm giới từ cố định', 'B2', 'She succeeded ___ passing the exam.', ['in', 'to', 'at', 'on'], 0, 'succeed IN + V-ing.'),

        // ==================== CÁC THÌ ====================
        q('present-simple', 'Present Simple', 'A1', 'She ___ English every day.', ['learns', 'learn', 'learning', 'is learn'], 0, 'Chủ ngữ ngôi thứ ba số ít (she) → động từ thêm "-s".'),
        q('present-simple', 'Present Simple', 'A1', 'Water ___ at 100°C.', ['boils', 'boil', 'is boiling', 'boiled'], 0, 'Chân lý khoa học luôn dùng Present Simple.'),
        q('present-simple', 'Present Simple', 'A1', 'I ___ coffee every morning.', ['drink', 'drinks', 'am drinking', 'drank'], 0, 'Ngôi "I" không thêm "-s"; thói quen dùng Present Simple.'),
        q('present-simple', 'Present Simple', 'A1', 'He ___ to work by bus.', ['goes', 'go', 'gos', 'going'], 0, 'Động từ tận cùng -o thêm "-es": go → goes.'),
        q('present-simple', 'Present Simple', 'A2', 'She ___ like coffee.', ['doesn\'t', 'don\'t', 'isn\'t', 'not'], 0, 'Phủ định ngôi thứ ba số ít: doesn\'t + V nguyên mẫu.'),
        q('present-simple', 'Present Simple', 'A2', '___ your brother work here?', ['Does', 'Do', 'Is', 'Are'], 0, 'Câu hỏi với chủ ngữ số ít: Does + S + V nguyên mẫu?'),
        q('present-simple', 'Present Simple', 'A2', 'My flight ___ at 7 a.m. tomorrow. (lịch trình cố định)', ['leaves', 'is leaving', 'will leave', 'left'], 0, 'Lịch trình, thời khóa biểu cố định trong tương lai dùng Present Simple.'),

        q('present-continuous', 'Present Continuous', 'A1', 'Look! The children ___ in the garden.', ['are playing', 'play', 'plays', 'played'], 0, '"Look!" báo hiệu hành động đang diễn ra ngay lúc nói.'),
        q('present-continuous', 'Present Continuous', 'A1', 'Right now, she ___ for the exam.', ['is studying', 'studies', 'study', 'studied'], 0, '"Right now" → Present Continuous.'),
        q('present-continuous', 'Present Continuous', 'A2', 'We ___ a lot of meetings this week.', ['are having', 'have', 'has', 'had'], 0, 'Tình huống tạm thời trong giai đoạn hiện tại → Present Continuous.'),
        q('present-continuous', 'Present Continuous', 'A2', 'I ___ dinner with Lan tomorrow. (đã hẹn trước)', ['am having', 'have', 'will have', 'had'], 0, 'Kế hoạch đã sắp xếp chắc chắn dùng Present Continuous cho tương lai gần.'),
        q('present-continuous', 'Present Continuous', 'B1', 'He ___ always ___ his keys! (phàn nàn)', ['is / losing', 'is / lost', 'does / lose', 'has / lost'], 0, 'Present Continuous + always diễn tả sự bực mình về thói quen lặp lại.'),
        q('stative-verbs', 'Động từ trạng thái', 'B1', 'I ___ this song. It\'s my favourite.', ['love', 'am loving', 'loves', 'am love'], 0, 'Động từ trạng thái (love, know, believe, want) thường không chia tiếp diễn.'),
        q('stative-verbs', 'Động từ trạng thái', 'B1', 'She ___ the answer now.', ['knows', 'is knowing', 'know', 'is know'], 0, '"know" là động từ trạng thái, không dùng dạng tiếp diễn.'),
        q('stative-verbs', 'Động từ trạng thái', 'B2', '"I\'m thinking about your offer" nghĩa là gì?', ['Tôi đang cân nhắc (hành động)', 'Tôi cho rằng (ý kiến)', 'Tôi biết rõ', 'Tôi đồng ý'], 0, '"think" ở dạng tiếp diễn = đang suy nghĩ/cân nhắc; ở dạng đơn = cho rằng.'),
        q('stative-verbs', 'Động từ trạng thái', 'B2', 'This soup ___ delicious.', ['tastes', 'is tasting', 'taste', 'is taste'], 0, 'Động từ giác quan mô tả trạng thái dùng thì đơn: tastes.'),

        q('past-simple', 'Past Simple', 'A1', 'Yesterday, I ___ to the market.', ['went', 'go', 'gone', 'have gone'], 0, '"Yesterday" là mốc quá khứ xác định → Past Simple.'),
        q('past-simple', 'Past Simple', 'A1', 'She ___ the film last night.', ['watched', 'watch', 'watchs', 'has watched'], 0, 'Động từ có quy tắc thêm "-ed" ở quá khứ đơn.'),
        q('past-simple', 'Past Simple', 'A2', 'They ___ to school yesterday.', ['didn\'t go', 'didn\'t went', 'don\'t go', 'not went'], 0, 'Phủ định quá khứ: didn\'t + V nguyên mẫu (không chia lại động từ).'),
        q('past-simple', 'Past Simple', 'A2', '___ you finish the report yesterday?', ['Did', 'Do', 'Have', 'Were'], 0, 'Câu hỏi quá khứ đơn: Did + S + V nguyên mẫu?'),
        q('past-simple', 'Past Simple', 'A2', 'Quá khứ của "buy" là:', ['bought', 'buyed', 'boughted', 'buys'], 0, 'buy → bought → bought (bất quy tắc).'),
        q('past-simple', 'Past Simple', 'B1', 'He ___ in Da Nang for five years, but now he lives in Hue.', ['lived', 'has lived', 'lives', 'is living'], 0, 'Giai đoạn đã kết thúc hoàn toàn → Past Simple, không dùng Present Perfect.'),

        q('past-continuous', 'Past Continuous', 'A2', 'I ___ TV when the phone rang.', ['was watching', 'watched', 'watch', 'am watching'], 0, 'Hành động đang diễn ra thì bị hành động ngắn cắt ngang → Past Continuous.'),
        q('past-continuous', 'Past Continuous', 'A2', 'At 7 o\'clock yesterday, I ___ breakfast.', ['was having', 'had', 'have', 'am having'], 0, 'Một thời điểm cụ thể trong quá khứ → hành động đang diễn ra lúc đó.'),
        q('past-continuous', 'Past Continuous', 'B1', 'While I ___ dinner, the lights went out.', ['was cooking', 'cooked', 'cook', 'have cooked'], 0, '"while" thường đi với Past Continuous cho hành động nền.'),
        q('past-continuous', 'Past Continuous', 'B1', 'They ___ while she ___.', ['were talking / was writing', 'talked / wrote', 'were talking / wrote', 'talked / was writing'], 0, 'Hai hành động cùng kéo dài song song trong quá khứ đều dùng Past Continuous.'),

        q('present-perfect', 'Present Perfect', 'A2', 'I ___ this book three times.', ['have read', 'read', 'am reading', 'was reading'], 0, 'Trải nghiệm tính đến hiện tại, số lần chưa khép lại → Present Perfect.'),
        q('present-perfect', 'Present Perfect', 'A2', 'She ___ here since 2020.', ['has worked', 'works', 'worked', 'is working'], 0, '"since + mốc thời gian" là dấu hiệu điển hình của Present Perfect.'),
        q('present-perfect', 'Present Perfect', 'A2', '___ you ever been to Japan?', ['Have', 'Has', 'Did', 'Do'], 0, 'Câu hỏi trải nghiệm với "ever": Have/Has + S + V3?'),
        q('present-perfect', 'Present Perfect', 'B1', 'I ___ my homework yet.', ['haven\'t finished', 'have finished', 'didn\'t finish', 'don\'t finish'], 0, '"yet" đi với câu phủ định hoặc câu hỏi của Present Perfect: haven\'t ... yet.'),
        q('present-perfect', 'Present Perfect', 'B1', 'She ___ already ___ the email.', ['has / sent', 'have / sent', 'has / send', 'did / send'], 0, '"already" đứng giữa trợ động từ và V3 trong Present Perfect.'),
        q('present-perfect', 'Present Perfect', 'B1', 'For hay since – chọn câu ĐÚNG:', ['I have lived here for ten years.', 'I have lived here since ten years.', 'I live here for ten years.', 'I am living here for ten years.'], 0, 'for + khoảng thời gian; since + mốc thời gian. Không nói "since ten years".'),
        q('present-perfect', 'Present Perfect', 'B1', 'Câu nào KHÔNG dùng được với Present Perfect?', ['yesterday', 'just', 'recently', 'so far'], 0, 'Trạng ngữ chỉ thời gian quá khứ xác định (yesterday, last week, in 2010) đi với Past Simple.'),
        q('present-perfect-continuous', 'Present Perfect Continuous', 'B1', 'I ___ English for three years and I still study it.', ['have been learning', 'have learned', 'learned', 'am learning'], 0, 'Nhấn mạnh quá trình kéo dài từ quá khứ đến hiện tại và còn tiếp tục.'),
        q('present-perfect-continuous', 'Present Perfect Continuous', 'B1', 'How long ___ you ___ here?', ['have / been waiting', 'did / wait', 'are / waiting', 'do / wait'], 0, 'Hỏi độ dài của hành động còn kéo dài: How long have you been + V-ing?'),
        q('present-perfect-continuous', 'Present Perfect Continuous', 'B2', 'Your eyes are red. ___ you ___?', ['Have / been crying', 'Did / cry', 'Are / crying', 'Do / cry'], 0, 'Nhìn kết quả hiện tại để suy ra hành động vừa kéo dài → Present Perfect Continuous.'),
        q('present-perfect-continuous', 'Present Perfect Continuous', 'B2', 'Chọn câu nhấn mạnh KẾT QUẢ, không phải quá trình:', ['I have written three reports.', 'I have been writing reports all day.', 'I have been writing since 9 a.m.', 'I have been writing a lot.'], 0, 'Present Perfect (have written) nhấn kết quả/số lượng hoàn tất; dạng tiếp diễn nhấn quá trình.'),

        q('past-perfect', 'Past Perfect', 'B1', 'By the time I ___ the station, the train had already left.', ['reached', 'reach', 'have reached', 'had reached'], 0, 'Mệnh đề "by the time" dùng Past Simple; hành động xảy ra TRƯỚC đó mới dùng Past Perfect.'),
        q('past-perfect', 'Past Perfect', 'B1', 'She ___ the work before I arrived.', ['had finished', 'finished', 'has finished', 'was finishing'], 0, 'Hành động hoàn tất trước một mốc quá khứ khác → Past Perfect.'),
        q('past-perfect', 'Past Perfect', 'B2', 'When we got to the cinema, the film ___.', ['had started', 'started', 'has started', 'was starting'], 0, 'Phim bắt đầu TRƯỚC khi chúng tôi tới → Past Perfect.'),
        q('past-perfect', 'Past Perfect', 'B2', 'He told me he ___ his passport.', ['had lost', 'has lost', 'lost', 'loses'], 0, 'Trong tường thuật, Present Perfect / Past Simple lùi thành Past Perfect.'),
        q('past-perfect-continuous', 'Past Perfect Continuous', 'B2', 'She was tired because she ___ all night.', ['had been driving', 'had driven', 'was driving', 'has been driving'], 0, 'Nhấn quá trình kéo dài trước một mốc quá khứ → had been + V-ing.'),
        q('past-perfect-continuous', 'Past Perfect Continuous', 'C1', 'They ___ for two hours when the manager finally arrived.', ['had been waiting', 'have been waiting', 'were waiting', 'waited'], 0, 'Khoảng thời gian kéo dài đến một mốc trong quá khứ → Past Perfect Continuous.'),

        q('future-simple', 'Future Simple', 'A2', 'I think it ___ tomorrow.', ['will rain', 'rains', 'is raining', 'rained'], 0, 'Dự đoán chủ quan với think/believe → will + V.'),
        q('future-simple', 'Future Simple', 'A2', 'The phone is ringing. I ___ it. (quyết định ngay lúc nói)', ['will answer', 'am going to answer', 'answer', 'am answering'], 0, 'Quyết định tức thời tại thời điểm nói dùng "will".'),
        q('future-simple', 'Future Simple', 'A2', 'There ___ a meeting next week.', ['will be', 'is', 'are', 'will'], 0, 'Tương lai của "There is/are" là "There will be".'),
        q('near-future', 'Be going to', 'A2', 'Look at those clouds! It ___ rain.', ['is going to', 'will', 'shall', 'would'], 0, 'Có bằng chứng hiện tại rõ ràng → be going to.'),
        q('will-vs-going-to', 'Will vs Going to', 'B1', 'I\'ve decided. I ___ study abroad next year.', ['am going to', 'will', 'would', 'shall'], 0, 'Dự định đã quyết định từ trước → be going to.'),
        q('will-vs-going-to', 'Will vs Going to', 'B1', 'Chọn câu diễn tả LỜI HỨA:', ['I will call you as soon as I arrive.', 'I am calling you as soon as I arrive.', 'I call you as soon as I arrive.', 'I am going to call you tomorrow anyway.'], 0, '"will" dùng cho lời hứa, đề nghị và quyết định tức thời.'),
        q('future-continuous', 'Future Continuous', 'B1', 'At this time tomorrow, I ___ at the airport.', ['will be waiting', 'will wait', 'am waiting', 'wait'], 0, 'Hành động đang diễn ra tại một thời điểm cụ thể trong tương lai.'),
        q('future-continuous', 'Future Continuous', 'B2', 'Don\'t call at 8 – we ___ dinner then.', ['will be having', 'will have', 'have', 'are having'], 0, 'Dự đoán hành động đang diễn ra vào một thời điểm tương lai.'),
        q('future-perfect', 'Future Perfect', 'B2', 'By next year, she ___ here for five years.', ['will have worked', 'will work', 'works', 'worked'], 0, 'Hoàn tất trước một mốc tương lai: will have + V3.'),
        q('future-perfect', 'Future Perfect', 'B2', 'By the time you arrive, I ___ everything.', ['will have prepared', 'will prepare', 'prepare', 'am preparing'], 0, '"By the time + hiện tại đơn" đi với Future Perfect ở mệnh đề chính.'),
        q('future-perfect-continuous', 'Future Perfect Continuous', 'C1', 'By June, they ___ on this project for a year.', ['will have been working', 'will have worked', 'will be working', 'will work'], 0, 'Nhấn độ dài liên tục tính đến một mốc tương lai: will have been + V-ing.'),
        q('sequence-of-tenses', 'Phối hợp thì', 'B1', 'I will call you when I ___ home.', ['get', 'will get', 'am getting', 'got'], 0, 'Mệnh đề thời gian (when, after, as soon as) KHÔNG dùng "will"; dùng hiện tại đơn.'),
        q('sequence-of-tenses', 'Phối hợp thì', 'B1', 'As soon as she ___ the news, she called me.', ['heard', 'hears', 'will hear', 'has heard'], 0, 'Mệnh đề chính ở quá khứ thì mệnh đề thời gian cũng lùi về quá khứ.'),
        q('sequence-of-tenses', 'Phối hợp thì', 'B2', 'If it ___ tomorrow, we will cancel the trip.', ['rains', 'will rain', 'rained', 'is raining'], 0, 'Mệnh đề "if" loại 1 dùng hiện tại đơn, không dùng "will".'),
        q('used-to', 'Used to / Be used to', 'B1', 'I ___ smoke, but I quit five years ago.', ['used to', 'am used to', 'use to', 'was used to'], 0, 'used to + V nguyên mẫu = thói quen trong quá khứ, nay không còn.'),
        q('used-to', 'Used to / Be used to', 'B2', 'She is used to ___ up early.', ['getting', 'get', 'got', 'gets'], 0, 'be used to + V-ing = đã quen với việc gì (khác hẳn "used to + V").'),
        q('used-to', 'Used to / Be used to', 'B2', 'It took a while, but he got used to ___ in a big city.', ['living', 'live', 'lived', 'lives'], 0, 'get used to + V-ing = dần quen với.'),
        q('have-got', 'Have got', 'A1', '___ you got any brothers?', ['Have', 'Do', 'Are', 'Has'], 0, 'Câu hỏi với "have got": Have/Has + S + got...?'),

        // ==================== MODAL & ĐIỀU KIỆN ====================
        q('modal-verbs', 'Động từ khiếm khuyết', 'A2', 'You ___ wear a helmet when riding a motorbike. (luật bắt buộc)', ['must', 'can', 'may', 'might'], 0, 'Nghĩa vụ bắt buộc do quy định → must.'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'A2', 'You ___ study harder. Your grades are low. (lời khuyên)', ['should', 'must', 'can', 'may'], 0, 'Lời khuyên → should. Lưu ý: KHÔNG có "should to".'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'A2', '___ I help you?', ['Can', 'Must', 'Should', 'Will'], 0, 'Đề nghị giúp đỡ lịch sự: Can/May I help you?'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'B1', 'It ___ rain later. I\'m not sure.', ['might', 'must', 'will definitely', 'can'], 0, 'Khả năng không chắc chắn → might/may.'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'B1', 'You ___ drive after drinking alcohol. (cấm tuyệt đối)', ['mustn\'t', 'don\'t have to', 'needn\'t', 'shouldn\'t have'], 0, 'mustn\'t = cấm; don\'t have to = không cần thiết. Hai nghĩa hoàn toàn khác nhau.'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'B1', 'It\'s Sunday, so you ___ get up early.', ['don\'t have to', 'mustn\'t', 'shouldn\'t', 'can\'t'], 0, '"don\'t have to" = không bắt buộc, muốn thì vẫn làm được.'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'B2', 'The light is on, so she ___ be at home. (suy đoán gần như chắc chắn)', ['must', 'can', 'should', 'might not'], 0, 'must + V = suy đoán chắc chắn dựa trên bằng chứng.'),
        q('modal-verbs', 'Động từ khiếm khuyết', 'B2', 'He ___ be at work – I just saw him at the beach.', ['can\'t', 'mustn\'t', 'shouldn\'t', 'may not'], 0, 'Suy đoán phủ định chắc chắn dùng "can\'t", không dùng "mustn\'t".'),
        q('modal-perfect', 'Modal + have + V3', 'B2', 'You ___ told me earlier! I was worried all night.', ['should have', 'should', 'must', 'would'], 0, 'should have + V3 = lẽ ra đã nên làm (nhưng đã không làm).'),
        q('modal-perfect', 'Modal + have + V3', 'B2', 'She isn\'t here. She ___ home already.', ['must have gone', 'must go', 'should go', 'can have gone'], 0, 'must have + V3 = chắc hẳn đã (suy đoán về quá khứ).'),
        q('modal-perfect', 'Modal + have + V3', 'C1', 'He ___ the message; he never checks his phone.', ['might not have seen', 'might not see', 'mustn\'t have seen', 'shouldn\'t see'], 0, 'might not have + V3 = có lẽ đã không (suy đoán không chắc về quá khứ).'),
        q('modal-perfect', 'Modal + have + V3', 'C1', '"You needn\'t have bought milk" nghĩa là gì?', ['Bạn đã mua sữa, nhưng việc đó là không cần thiết.', 'Bạn đã không mua sữa.', 'Bạn không được phép mua sữa.', 'Bạn nên mua sữa.'], 0, 'needn\'t have + V3 = đã làm rồi nhưng hóa ra không cần.'),
        q('semi-modals', 'Bán khiếm khuyết', 'B2', 'You ___ to submit the form before Friday.', ['are supposed', 'are suppose', 'suppose', 'supposed'], 0, 'be supposed to + V = được cho là phải, theo quy định/kỳ vọng.'),
        q('semi-modals', 'Bán khiếm khuyết', 'B2', 'I ___ rather stay home tonight.', ['would', 'will', 'should', 'had better to'], 0, 'would rather + V nguyên mẫu = thà rằng, thích hơn.'),
        q('semi-modals', 'Bán khiếm khuyết', 'B2', 'You ___ better see a doctor.', ['had', 'would', 'should', 'have'], 0, 'had better + V nguyên mẫu = tốt hơn hết là (lời khuyên mạnh).'),

        q('conditionals', 'Câu điều kiện', 'A2', 'If you heat ice, it ___. (loại 0)', ['melts', 'will melt', 'melted', 'would melt'], 0, 'Điều kiện loại 0 (sự thật hiển nhiên): If + hiện tại đơn, hiện tại đơn.'),
        q('conditionals', 'Câu điều kiện', 'B1', 'If it ___ tomorrow, I will stay home.', ['rains', 'will rain', 'rained', 'is raining'], 0, 'Loại 1: If + hiện tại đơn, will + V nguyên mẫu.'),
        q('conditionals', 'Câu điều kiện', 'B1', 'If I ___ rich, I would buy a big house.', ['were', 'am', 'will be', 'have been'], 0, 'Loại 2 (giả định trái hiện tại): dùng "were" cho mọi ngôi.'),
        q('conditionals', 'Câu điều kiện', 'B1', 'If you ___ harder, you would pass the exam.', ['studied', 'study', 'will study', 'had studied'], 0, 'Loại 2: If + quá khứ đơn, would + V.'),
        q('conditionals', 'Câu điều kiện', 'B2', 'If I ___ the news, I would have told you.', ['had known', 'knew', 'know', 'have known'], 0, 'Loại 3 (tiếc nuối quá khứ): If + Past Perfect, would have + V3.'),
        q('conditionals', 'Câu điều kiện', 'B2', '___ you need help, just call me.', ['Should', 'Would', 'Had', 'Were'], 0, 'Đảo ngữ trang trọng của loại 1: Should + S + V = If S should V.'),
        q('conditionals', 'Câu điều kiện', 'B2', '___ we will cancel the trip.', ['If it rains,', 'If it will rain,', 'If it rained,', 'If it would rain,'], 0, 'Mệnh đề "if" loại 1 không bao giờ dùng "will".'),
        q('conditionals', 'Câu điều kiện', 'B2', '___ you study, you will fail.', ['Unless', 'If', 'When', 'Because'], 0, 'Unless = If ... not (trừ khi). Bản thân "unless" đã mang nghĩa phủ định.'),
        q('mixed-conditionals', 'Điều kiện hỗn hợp', 'C1', 'If I ___ harder at school, I would have a better job now.', ['had studied', 'studied', 'study', 'would study'], 0, 'Hỗn hợp 3→2: điều kiện quá khứ (had + V3) dẫn tới kết quả ở hiện tại (would + V).'),
        q('mixed-conditionals', 'Điều kiện hỗn hợp', 'C1', 'If she ___ more careful, she wouldn\'t have made that mistake.', ['were', 'had been', 'is', 'would be'], 0, 'Hỗn hợp 2→3: tính cách ở hiện tại (were) dẫn tới hậu quả trong quá khứ (would have + V3).'),
        q('wish-if-only', 'Wish / If only', 'B2', 'I wish I ___ richer.', ['were', 'am', 'will be', 'have been'], 0, 'Wish về hiện tại không có thật: lùi một thì, dùng "were" cho mọi ngôi.'),
        q('wish-if-only', 'Wish / If only', 'B2', 'I wish I ___ harder for the last exam.', ['had studied', 'studied', 'study', 'would study'], 0, 'Tiếc nuối về quá khứ → wish + Past Perfect.'),
        q('wish-if-only', 'Wish / If only', 'B2', 'I wish he ___ talking so loudly!', ['would stop', 'stops', 'stopped', 'had stopped'], 0, 'wish + would + V = mong người khác thay đổi hành vi gây khó chịu.'),
        q('wish-if-only', 'Wish / If only', 'C1', 'If only I ___ the truth then!', ['had known', 'knew', 'know', 'would know'], 0, '"If only" về quá khứ dùng Past Perfect, giống wish.'),

        // ==================== BỊ ĐỘNG & CAUSATIVE ====================
        q('passive-voice', 'Câu bị động', 'B1', 'The cake ___ by my mother.', ['was made', 'made', 'makes', 'is making'], 0, 'Bị động: S + be + V3 (+ by O).'),
        q('passive-voice', 'Câu bị động', 'B1', 'English ___ in many countries.', ['is spoken', 'speaks', 'is speaking', 'speaks by'], 0, 'Bị động hiện tại đơn: is/are + V3.'),
        q('passive-voice', 'Câu bị động', 'B1', 'The work ___ tomorrow.', ['will be completed', 'will complete', 'completes', 'is completing'], 0, 'Bị động tương lai: will be + V3.'),
        q('passive-voice', 'Câu bị động', 'B2', 'The road ___ at the moment.', ['is being repaired', 'is repairing', 'repairs', 'has repaired'], 0, 'Bị động của thì tiếp diễn: is being + V3.'),
        q('passive-voice', 'Câu bị động', 'B2', 'The report ___ already ___.', ['has / been submitted', 'has / submitted', 'is / submitted', 'was / been submitted'], 0, 'Bị động Present Perfect: have/has been + V3.'),
        q('passive-voice', 'Câu bị động', 'B2', 'Chuyển sang bị động: "They gave her a prize."', ['She was given a prize.', 'A prize was given her.', 'She was gave a prize.', 'A prize gave her.'], 0, 'Với động từ hai tân ngữ, tân ngữ chỉ người thường lên làm chủ ngữ bị động.'),
        q('passive-voice', 'Câu bị động', 'C1', 'It ___ that the company will merge next year.', ['is said', 'says', 'is saying', 'has said'], 0, 'Bị động vô nhân xưng: It is said/believed/reported that + mệnh đề.'),
        q('passive-voice', 'Câu bị động', 'C1', 'Chọn dạng bị động đúng của "People believe he is honest."', ['He is believed to be honest.', 'He is believed being honest.', 'He believes to be honest.', 'He is believing to be honest.'], 0, 'S + be + V3 + to V: cấu trúc bị động rút gọn trang trọng.'),

        q('causatives', 'Causative', 'B1', 'I had my car ___ last week.', ['repaired', 'repair', 'repairing', 'to repair'], 0, 'have + O + V3: nhờ/thuê người khác làm cho mình.'),
        q('causatives', 'Causative', 'B1', 'She got her husband ___ the groceries.', ['to buy', 'buy', 'buying', 'bought'], 0, 'get + O + TO V (khác với have + O + V nguyên mẫu).'),
        q('causatives', 'Causative', 'B1', 'The teacher made the students ___ the essay again.', ['write', 'to write', 'writing', 'written'], 0, 'make + O + V nguyên mẫu (không "to").'),
        q('causatives', 'Causative', 'B1', 'My parents let me ___ out with friends last night.', ['go', 'to go', 'going', 'gone'], 0, 'let + O + V nguyên mẫu (không "to").'),
        q('causatives', 'Causative', 'B1', 'I need to ___ my laptop ___ before the presentation.', ['have / fixed', 'have / fix', 'get / to fix', 'let / fixed'], 0, 'have + O + V3 = nhờ dịch vụ sửa giúp.'),
        q('causatives', 'Causative', 'B1', 'She ___ her nails done at the salon every weekend.', ['gets', 'makes', 'lets', 'does'], 0, 'get + O + V3 diễn tả đi làm dịch vụ.'),
        q('causatives', 'Causative', 'B2', 'He was ___ to apologise to the whole class.', ['made', 'let', 'got', 'had'], 0, 'Bị động của "make" khôi phục "to": be made TO + V.'),
        q('causatives', 'Causative', 'B2', 'We had the broken window ___ by a professional.', ['replaced', 'replace', 'replacing', 'to replace'], 0, 'have + O + V3 + by somebody.'),
        q('causatives', 'Causative', 'B2', 'I finally ___ the landlord to fix the leaking pipe.', ['got', 'made', 'let', 'had'], 0, 'Có "to fix" trong câu nên chỉ "get" hợp: get + O + to V (thuyết phục được ai đó).'),
        q('causatives', 'Causative', 'B2', 'The manager ___ the team work overtime last Friday.', ['made', 'got', 'allowed', 'forced'], 0, 'Không có "to" trước "work" nên chỉ "made" đúng: make + O + V nguyên mẫu.'),
        q('causatives', 'Causative', 'B2', '"He had his teeth ___." Chọn dạng đúng.', ['checked', 'check', 'checking', 'to check'], 0, 'have + O + V3 = đi khám/chăm sóc răng (dịch vụ).'),
        q('causatives', 'Causative', 'B2', 'The news made her ___.', ['cry', 'to cry', 'cried', 'crying'], 0, 'make + O + V nguyên mẫu, kể cả khi diễn tả cảm xúc.'),
        q('causatives', 'Causative', 'B2', 'I\'ll have Tom ___ the report before the meeting.', ['check', 'to check', 'checked', 'checking'], 0, 'have + NGƯỜI + V nguyên mẫu (giao việc trực tiếp) ≠ have + VẬT + V3.'),
        q('causatives', 'Causative', 'B2', 'Students are usually ___ to use dictionaries during the exam.', ['allowed', 'let', 'made', 'got'], 0, '"let" không có dạng bị động; thay bằng "be allowed to".'),
        q('causatives', 'Causative', 'B2', 'I had my wallet ___ while I was on the train.', ['stolen', 'steal', 'stole', 'stealing'], 0, 'have + O + V3 còn diễn tả điều không may xảy đến với mình.'),
        q('causatives', 'Causative', 'B2', 'I\'m going to ___ my hair ___ this weekend.', ['get / cut', 'have / cutting', 'let / cut', 'make / to cut'], 0, 'get + O + V3 cho dịch vụ: get my hair cut.'),
        q('causatives', 'Causative', 'B2', 'They didn\'t let us ___ photos inside the museum.', ['take', 'to take', 'taking', 'took'], 0, 'Dạng phủ định vẫn giữ let + O + V nguyên mẫu.'),
        q('causatives', 'Causative', 'B2', 'You should ___ your car ___ before the long trip.', ['have / serviced', 'get / service', 'make / serviced', 'let / servicing'], 0, 'Sau modal, causative giữ nguyên: should have + O + V3.'),
        q('causatives', 'Causative', 'B2', 'Câu nào đồng nghĩa với "A mechanic repaired my bike for me."?', ['I had my bike repaired.', 'I repaired my bike.', 'I was repaired my bike.', 'I made my bike repaired.'], 0, 'Nhờ người khác làm giúp = have + O + V3.'),
        q('causatives', 'Causative', 'B2', 'She helped him ___ the boxes upstairs.', ['carry', 'carried', 'carrying', 'to carrying'], 0, 'help + O + V nguyên mẫu (hoặc "to carry"), nhưng không dùng V-ing hay "to carrying".'),

        // ==================== MỆNH ĐỀ ====================
        q('relative-clauses', 'Mệnh đề quan hệ', 'B1', 'The man ___ helped us is my uncle.', ['who', 'which', 'whose', 'where'], 0, 'Chủ ngữ chỉ người → "who" (hoặc "that"). "which" chỉ dùng cho vật.'),
        q('relative-clauses', 'Mệnh đề quan hệ', 'B1', 'The book ___ I bought yesterday is interesting.', ['which', 'who', 'whose', 'whom'], 0, 'Tân ngữ chỉ vật → "which" (hoặc "that"). Không dùng "who" cho vật.'),
        q('relative-clauses', 'Mệnh đề quan hệ', 'B1', 'That\'s the girl ___ father is a doctor.', ['whose', 'who', 'which', 'whom'], 0, '"whose" chỉ quan hệ sở hữu: cô gái mà BỐ CỦA cô ấy...'),
        q('relative-clauses', 'Mệnh đề quan hệ', 'B1', 'The city ___ I live is beautiful.', ['where', 'which', 'that', 'when'], 0, 'Trạng ngữ nơi chốn → "where" (= in which). "which" trần trụi thì sai.'),
        q('relative-clauses', 'Mệnh đề quan hệ', 'B2', 'Câu nào dùng mệnh đề KHÔNG xác định đúng?', ['My brother, who lives in Hue, is a teacher.', 'My brother, that lives in Hue, is a teacher.', 'My brother who lives in Hue is a teacher, and I have one brother.', 'My brother, which lives in Hue, is a teacher.'], 0, 'Mệnh đề không xác định có dấu phẩy và KHÔNG bao giờ dùng "that".'),
        q('relative-clauses', 'Mệnh đề quan hệ', 'B2', 'Trong câu nào có thể LƯỢC BỎ đại từ quan hệ?', ['The film (that) we watched was great.', 'The man who lives here is kind.', 'The book which is on the table is mine.', 'The girl whose bag was stolen cried.'], 0, 'Chỉ lược bỏ được khi đại từ quan hệ làm TÂN NGỮ của mệnh đề.'),
        q('reduced-relatives', 'Rút gọn mệnh đề quan hệ', 'B2', 'Rút gọn: "The man who is standing there is my boss."', ['The man standing there is my boss.', 'The man stood there is my boss.', 'The man to stand there is my boss.', 'The man stand there is my boss.'], 0, 'Mệnh đề quan hệ chủ động rút thành V-ing.'),
        q('reduced-relatives', 'Rút gọn mệnh đề quan hệ', 'B2', 'Rút gọn: "The letter which was written by Lan arrived."', ['The letter written by Lan arrived.', 'The letter writing by Lan arrived.', 'The letter to write by Lan arrived.', 'The letter wrote by Lan arrived.'], 0, 'Mệnh đề quan hệ bị động rút thành V3 (past participle).'),
        q('reduced-relatives', 'Rút gọn mệnh đề quan hệ', 'C1', 'Rút gọn: "He was the first person who arrived."', ['He was the first person to arrive.', 'He was the first person arriving.', 'He was the first person arrived.', 'He was the first person for arriving.'], 0, 'Sau the first/last/only/so sánh nhất, rút gọn thành "to + V".'),

        q('noun-clauses', 'Mệnh đề danh từ', 'B2', '___ she is absent is not clear.', ['That', 'What', 'Which', 'Who'], 0, '"That + mệnh đề" làm chủ ngữ, không mang nghĩa hỏi.'),
        q('noun-clauses', 'Mệnh đề danh từ', 'B2', 'I don\'t know ___ she will come or not.', ['whether', 'if', 'that', 'what'], 0, 'Chỉ "whether" đi được với "or not" ngay sau nó; "if ... or not" phải tách xa.'),
        q('noun-clauses', 'Mệnh đề danh từ', 'B2', '___ he said surprised everyone.', ['What', 'That', 'Which', 'Whether'], 0, '"What" = điều mà (bao gồm cả tiền ngữ), làm chủ ngữ của câu.'),
        q('embedded-questions', 'Câu hỏi gián tiếp', 'B2', 'Could you tell me ___?', ['where the station is', 'where is the station', 'where the station is?', 'where is the station is'], 0, 'Câu hỏi lồng trong câu khác giữ trật tự S + V, không đảo ngữ.'),
        q('embedded-questions', 'Câu hỏi gián tiếp', 'B2', 'I wonder ___.', ['what time the meeting starts', 'what time does the meeting start', 'what time starts the meeting', 'what time the meeting does start'], 0, 'Không dùng trợ động từ do/does trong mệnh đề hỏi gián tiếp.'),

        q('adverbial-time-clauses', 'Mệnh đề trạng ngữ', 'B1', 'I will call you ___ I arrive.', ['when', 'while', 'during', 'since'], 0, '"when" nối với một thời điểm; "during" là giới từ, phải đi với danh từ.'),
        q('adverbial-time-clauses', 'Mệnh đề trạng ngữ', 'B1', '___ she was sleeping, the phone rang.', ['While', 'During', 'Since', 'Until'], 0, '"While + mệnh đề" cho hành động kéo dài; "During + danh từ".'),
        q('adverbial-time-clauses', 'Mệnh đề trạng ngữ', 'B1', 'We stayed inside ___ the storm.', ['during', 'while', 'when', 'as soon as'], 0, '"during" là giới từ nên theo sau là danh từ (the storm).'),
        q('adverbial-time-clauses', 'Mệnh đề trạng ngữ', 'B2', '___ she was tired, she still finished her work.', ['Although', 'Because', 'So', 'Therefore'], 0, 'Nhượng bộ → Although/Though/Even though + mệnh đề.'),
        q('adverbial-time-clauses', 'Mệnh đề trạng ngữ', 'B2', '___ her hard work, she failed the test.', ['Despite', 'Although', 'Because', 'However'], 0, '"Despite/In spite of" + danh từ; "Although" + mệnh đề.'),
        q('reducing-adverbial-clauses', 'Rút gọn mệnh đề trạng ngữ', 'C1', 'Rút gọn: "Because he was tired, he went to bed early."', ['Being tired, he went to bed early.', 'Been tired, he went to bed early.', 'To be tired, he went to bed early.', 'Was tired, he went to bed early.'], 0, 'Cùng chủ ngữ → rút mệnh đề nguyên nhân thành phân từ V-ing.'),
        q('participle-clauses', 'Mệnh đề phân từ', 'C1', '___ the door, she noticed a strange smell.', ['Opening', 'Opened', 'To open', 'Open'], 0, 'Phân từ hiện tại diễn tả hành động chủ động cùng chủ ngữ với mệnh đề chính.'),
        q('participle-clauses', 'Mệnh đề phân từ', 'C1', '___ in 1990, the building is now a museum.', ['Built', 'Building', 'To build', 'Build'], 0, 'Phân từ quá khứ mang nghĩa bị động: (Having been) built in 1990.'),
        q('participle-clauses', 'Mệnh đề phân từ', 'C1', '___ the report, he sent it to his boss.', ['Having finished', 'Finishing', 'Finished', 'To finish'], 0, 'Having + V3 nhấn hành động hoàn tất TRƯỚC hành động chính.'),

        q('result-structures', 'Cấu trúc kết quả', 'B1', 'It was ___ a difficult test that nobody passed.', ['such', 'so', 'too', 'very'], 0, 'such + (a/an) + adj + noun + that; so + adj + that.'),
        q('result-structures', 'Cấu trúc kết quả', 'B1', 'The test was ___ difficult that nobody passed.', ['so', 'such', 'too', 'very'], 0, 'so + tính từ (không có danh từ theo sau) + that.'),
        q('result-structures', 'Cấu trúc kết quả', 'B2', 'He spoke ___ quickly ___ nobody understood him.', ['so / that', 'such / that', 'too / to', 'very / that'], 0, 'so + trạng từ + that + mệnh đề kết quả.'),

        // ==================== CÂU HỎI, PHỦ ĐỊNH, TƯỜNG THUẬT ====================
        q('question-forms', 'Câu hỏi', 'A1', '___ is her name? – Her name is Lan.', ['What', 'Who', 'Where', 'How'], 0, 'Hỏi tên gọi → What.'),
        q('question-forms', 'Câu hỏi', 'A1', '___ is she from? – She is from Vietnam.', ['Where', 'What', 'Who', 'How'], 0, 'Hỏi nơi xuất xứ → Where.'),
        q('question-forms', 'Câu hỏi', 'A2', '___ does the book cost? – Twenty dollars.', ['How much', 'How many', 'How long', 'How often'], 0, 'Hỏi giá tiền → How much.'),
        q('question-forms', 'Câu hỏi', 'A2', '___ did you study English? – For three years.', ['How long', 'How often', 'How much', 'When'], 0, 'Hỏi khoảng thời gian kéo dài → How long.'),
        q('question-forms', 'Câu hỏi', 'A2', '___ do you go to the gym? – Twice a week.', ['How often', 'How long', 'How much', 'When'], 0, 'Hỏi tần suất → How often.'),
        q('wh-questions', 'Câu hỏi Wh-', 'B1', '___ broke the window? – Nam did.', ['Who', 'Whom', 'Whose', 'What did'], 0, 'Khi từ để hỏi CHÍNH LÀ chủ ngữ, không dùng trợ động từ: "Who broke...?"'),
        q('wh-questions', 'Câu hỏi Wh-', 'B1', '___ did you meet at the party?', ['Who', 'Whose', 'Which', 'What did'], 0, 'Hỏi về tân ngữ chỉ người, cần trợ động từ "did" + V nguyên mẫu.'),
        q('yes-no-questions', 'Câu hỏi Yes/No', 'A2', '___ she finished her homework?', ['Has', 'Have', 'Is', 'Does'], 0, 'Present Perfect ngôi thứ ba số ít: Has + S + V3?'),
        q('negatives', 'Câu phủ định', 'A1', 'I ___ go to the party tonight.', ['am not going to', 'am not', 'not', 'doesn\'t'], 0, 'Với "go" nguyên mẫu, phủ định phải là "don\'t go" hoặc "am not going to go".'),
        q('negatives', 'Câu phủ định', 'A2', 'She ___ any money.', ['doesn\'t have', 'don\'t have', 'hasn\'t any', 'not have'], 0, 'Ngôi thứ ba số ít: doesn\'t + V nguyên mẫu.'),
        q('negatives', 'Câu phủ định', 'B1', 'Phủ định kép – chọn câu ĐÚNG:', ['I don\'t know anything about it.', 'I don\'t know nothing about it.', 'I know not anything about it.', 'I don\'t know none about it.'], 0, 'Tiếng Anh chuẩn không dùng phủ định kép: don\'t + anything.'),
        q('negation-patterns', 'Phủ định nâng cao', 'B2', 'Hòa hợp với "neither of" – chọn câu ĐÚNG:', ['Neither of them was invited.', 'Neither of them were invite.', 'None of them was invite.', 'Neither them was invited.'], 0, '"Neither of + danh từ số nhiều" đi với động từ số ít trong văn viết chuẩn.'),
        q('tag-questions', 'Câu hỏi đuôi', 'B1', 'She is a teacher, ___?', ['isn\'t she', 'is she', 'doesn\'t she', 'does she'], 0, 'Mệnh đề khẳng định → đuôi phủ định, lặp lại trợ động từ "is".'),
        q('tag-questions', 'Câu hỏi đuôi', 'B1', 'You don\'t smoke, ___?', ['do you', 'don\'t you', 'are you', 'did you'], 0, 'Mệnh đề phủ định → đuôi khẳng định.'),
        q('tag-questions', 'Câu hỏi đuôi', 'B2', 'Let\'s go out tonight, ___?', ['shall we', 'will we', 'do we', 'don\'t we'], 0, 'Sau "Let\'s", câu hỏi đuôi luôn là "shall we?".'),
        q('tag-questions', 'Câu hỏi đuôi', 'B2', 'I am late, ___?', ['aren\'t I', 'am not I', 'amn\'t I', 'don\'t I'], 0, 'Ngoại lệ cố định: "I am..." → đuôi "aren\'t I?".'),
        q('tag-questions', 'Câu hỏi đuôi', 'B2', 'Nobody called, ___?', ['did they', 'didn\'t they', 'did he', 'didn\'t nobody'], 0, '"Nobody" đã mang nghĩa phủ định → đuôi khẳng định, đại từ "they".'),

        q('reported-speech', 'Câu tường thuật', 'B1', '"I am tired," she said. → She said ___ tired.', ['she was', 'I was', 'she is', 'I am'], 0, 'Tường thuật phải đổi CẢ đại từ (I → she) và thì (am → was).'),
        q('reported-speech', 'Câu tường thuật', 'B1', '"I will come," he said. → He said he ___ come.', ['would', 'will', 'can', 'shall'], 0, 'Lùi thì: will → would.'),
        q('reported-speech', 'Câu tường thuật', 'B1', '"Where are you going?" he asked. → He asked ___.', ['where I was going', 'where was I going', 'where I am going', 'where am I going'], 0, 'Câu hỏi tường thuật giữ từ hỏi gốc (where), trật tự S + V, và lùi thì.'),
        q('reported-speech', 'Câu tường thuật', 'B2', '"Do you like coffee?" she asked. → She asked ___ coffee.', ['if I liked', 'do I like', 'if did I like', 'that I liked'], 0, 'Câu hỏi Yes/No tường thuật dùng "if/whether" + S + V lùi thì.'),
        q('reported-speech', 'Câu tường thuật', 'B2', '"Close the door," he said. → He told me ___ the door.', ['to close', 'close', 'closing', 'closed'], 0, 'Mệnh lệnh tường thuật: tell/ask somebody TO + V.'),
        q('reported-speech', 'Câu tường thuật', 'B2', '"Don\'t touch it," she said. → She told me ___ it.', ['not to touch', 'to not touch', 'don\'t touch', 'not touching'], 0, 'Mệnh lệnh phủ định: NOT + to + V.'),
        q('reported-speech', 'Câu tường thuật', 'B2', '"I saw him yesterday," she said. → She said she had seen him ___.', ['the day before', 'yesterday', 'tomorrow', 'the next day'], 0, 'Trạng ngữ thời gian cũng phải lùi: yesterday → the day before / the previous day.'),
        q('reported-speech', 'Câu tường thuật', 'C1', 'Câu nào KHÔNG cần lùi thì?', ['She said that water boils at 100°C.', 'She said that she was tired.', 'She said that she would come.', 'She said that she had finished.'], 0, 'Chân lý luôn đúng thì không bắt buộc lùi thì.'),

        // ==================== ĐỘNG TỪ NGUYÊN MẪU & DANH ĐỘNG TỪ ====================
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B1', 'I enjoy ___ English.', ['learning', 'to learn', 'learn', 'learned'], 0, 'enjoy, avoid, mind, finish, practise + V-ing.'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B1', 'She decided ___ the exam again.', ['to take', 'taking', 'take', 'taken'], 0, 'decide, hope, want, plan, promise, agree + to V.'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B1', 'I suggest ___ a break.', ['taking', 'to take', 'take', 'taken'], 0, 'suggest + V-ing (hoặc suggest that + S + V), không dùng "suggest to do".'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B1', 'I look forward to ___ you soon.', ['seeing', 'see', 'to see', 'seen'], 0, '"to" ở đây là giới từ nên theo sau là V-ing.'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B2', 'He stopped ___ because the doctor told him to quit.', ['smoking', 'to smoke', 'smoke', 'smoked'], 0, 'stop + V-ing = dừng hẳn việc đang làm. (stop to V = dừng lại ĐỂ làm việc khác.)'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B2', 'On the way home he stopped ___ some petrol.', ['to buy', 'buying', 'buy', 'bought'], 0, 'stop TO V = dừng lại với mục đích làm việc gì.'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B2', 'Remember ___ the door before you leave.', ['to lock', 'locking', 'lock', 'locked'], 0, 'remember TO V = nhớ phải làm (việc sắp tới). remember V-ing = nhớ đã từng làm.'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B2', 'I still remember ___ her for the first time.', ['meeting', 'to meet', 'meet', 'met'], 0, 'remember + V-ing = nhớ lại kỷ niệm đã xảy ra.'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'B2', 'I regret ___ you that your application was rejected.', ['to inform', 'informing', 'inform', 'informed'], 0, 'regret TO V (inform/say/tell) = tiếc phải thông báo (việc đang làm).'),
        q('gerunds-infinitives', 'Gerund / Infinitive', 'C1', 'The car needs ___.', ['washing', 'to washing', 'wash', 'washed to'], 0, 'need + V-ing mang nghĩa bị động: = needs to be washed.'),
        q('verb-patterns', 'Mẫu động từ', 'B2', 'She persuaded me ___ my mind.', ['to change', 'changing', 'change', 'changed'], 0, 'persuade / advise / encourage / remind + O + to V.'),
        q('verb-patterns', 'Mẫu động từ', 'B2', 'They accused him ___ the money.', ['of stealing', 'to steal', 'for stealing', 'that he stole'], 0, 'accuse somebody OF + V-ing.'),
        q('verb-patterns', 'Mẫu động từ', 'B2', 'She apologised ___ late.', ['for being', 'to be', 'of being', 'being'], 0, 'apologise FOR + V-ing.'),
        q('verb-patterns', 'Mẫu động từ', 'B2', 'I saw him ___ the building at 8 a.m. (thấy toàn bộ hành động)', ['enter', 'to enter', 'entered', 'enters'], 0, 'see/hear + O + V nguyên mẫu = chứng kiến trọn vẹn hành động.'),
        q('verb-patterns', 'Mẫu động từ', 'C1', 'I saw him ___ the street when I passed by. (thấy giữa chừng)', ['crossing', 'cross', 'crossed', 'to cross'], 0, 'see + O + V-ing = chứng kiến hành động đang diễn ra dở dang.'),
        q('infinitive-purposes', 'Nguyên mẫu chỉ mục đích', 'B1', 'I went to the shop ___ some bread.', ['to buy', 'for buy', 'for buying', 'buying'], 0, 'Chỉ mục đích dùng "to + V" hoặc "in order to + V", không dùng "for + V-ing".'),
        q('infinitive-purposes', 'Nguyên mẫu chỉ mục đích', 'B2', 'He left early ___ miss the traffic.', ['so as not to', 'so as to not', 'for not', 'not to as'], 0, 'Phủ định của "so as to" là "so as NOT to + V".'),

        // ==================== HÒA HỢP CHỦ NGỮ – ĐỘNG TỪ ====================
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B1', 'The news ___ very interesting.', ['is', 'are', 'were', 'have been'], 0, '"news" tận cùng bằng -s nhưng là danh từ số ít.'),
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B1', 'Ten dollars ___ too much for this.', ['is', 'are', 'were', 'have'], 0, 'Số tiền, khoảng cách, thời lượng coi là một khối → động từ số ít.'),
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B1', 'Mathematics ___ difficult for me.', ['is', 'are', 'were', 'have been'], 0, 'Tên môn học tận cùng -ics là số ít.'),
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B1', 'Each of the students ___ a different book.', ['has', 'have', 'having', 'are having'], 0, '"Each of + N số nhiều" luôn đi với động từ số ít.'),
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B2', 'Neither the teacher nor the students ___ present.', ['are', 'is', 'was', 'has been'], 0, 'Với either/neither...nor, động từ chia theo danh từ GẦN NHẤT (students).'),
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B2', 'The list of items ___ on the desk.', ['is', 'are', 'were', 'have been'], 0, 'Chủ ngữ thật là "the list"; cụm giới từ "of items" không đổi số.'),
        q('subject-verb-agreement', 'Hòa hợp S–V', 'B2', 'A number of students ___ absent today.', ['are', 'is', 'was', 'has been'], 0, '"A number of" = nhiều → số nhiều. ("The number of" mới là số ít.)'),
        q('advanced-agreement', 'Hòa hợp S–V nâng cao', 'C1', 'The number of applicants ___ increased.', ['has', 'have', 'are', 'were'], 0, '"The number of" là chủ ngữ số ít, trái ngược với "A number of".'),
        q('advanced-agreement', 'Hòa hợp S–V nâng cao', 'C1', 'The team ___ divided on this issue. (nhấn từng thành viên)', ['are', 'is', 'was', 'has'], 0, 'Danh từ tập hợp đi với động từ số nhiều khi nhấn vào các cá nhân trong nhóm.'),

        // ==================== LIÊN TỪ, DIỄN NGÔN, NHẤN MẠNH ====================
        q('conjunctions', 'Liên từ', 'A2', 'I study English ___ I want to work abroad.', ['because', 'although', 'but', 'so'], 0, 'Nêu lý do → because.'),
        q('conjunctions', 'Liên từ', 'A2', 'It was raining, ___ we stayed inside.', ['so', 'but', 'because', 'although'], 0, 'Nêu kết quả → so.'),
        q('conjunctions', 'Liên từ', 'A2', 'Would you like coffee ___ tea?', ['or', 'and', 'but', 'so'], 0, 'Đưa ra lựa chọn giữa hai thứ → or.'),
        q('conjunctions', 'Liên từ', 'B1', 'Chọn cặp liên từ đúng: "___ my sister ___ I can drive."', ['Both / and', 'Both / or', 'Either / and', 'Neither / or'], 0, 'Cặp cố định: both...and, either...or, neither...nor.'),
        q('conjunctions', 'Liên từ', 'B1', 'She is not only smart ___ hard-working.', ['but also', 'and also', 'but too', 'or also'], 0, 'Cặp cố định: not only ... but also.'),
        q('conjunctions', 'Liên từ', 'B2', 'Chọn câu dùng dấu câu ĐÚNG:', ['It was late; therefore, we went home.', 'It was late, therefore we went home.', 'It was late therefore, we went home.', 'It was late; therefore we went home,'], 0, 'Trạng từ liên kết (therefore, however) cần dấu chấm phẩy phía trước và dấu phẩy phía sau.'),
        q('discourse-markers', 'Từ nối văn bản', 'B2', 'The plan is expensive. ___, it may be the only option.', ['However', 'Moreover', 'Therefore', 'For example'], 0, '"However" báo hiệu ý tương phản với câu trước.'),
        q('discourse-markers', 'Từ nối văn bản', 'B2', 'She is talented. ___, she works extremely hard.', ['Moreover', 'However', 'Nevertheless', 'Otherwise'], 0, '"Moreover" bổ sung thêm một ý cùng chiều.'),
        q('discourse-markers', 'Từ nối văn bản', 'B2', 'Hurry up, ___ you will miss the train.', ['otherwise', 'however', 'therefore', 'moreover'], 0, '"otherwise" = nếu không thì (hậu quả tiêu cực).'),
        q('discourse-markers', 'Từ nối văn bản', 'C1', 'The results were poor. ___, the project continued.', ['Nonetheless', 'Consequently', 'Hence', 'Likewise'], 0, '"Nonetheless/Nevertheless" = tuy vậy, diễn tả sự tương phản trang trọng.'),
        q('do-emphasis', 'Nhấn mạnh với DO', 'B2', 'I ___ understand what you mean, but I still disagree.', ['do', 'does', 'did', 'am'], 0, 'do/does/did + V nguyên mẫu để nhấn mạnh ở thì hiện tại, ngôi "I".'),
        q('do-emphasis', 'Nhấn mạnh với DO', 'B2', 'She ___ try her best yesterday, but she failed.', ['did', 'does', 'do', 'was'], 0, '"yesterday" → dùng "did + V nguyên mẫu" để nhấn mạnh ở quá khứ.'),
        q('cleft-sentences', 'Câu chẻ', 'C1', '___ Lan who broke the vase.', ['It was', 'There was', 'That was', 'This was'], 0, 'Câu chẻ nhấn mạnh chủ ngữ: It + be + phần nhấn mạnh + who/that...'),
        q('cleft-sentences', 'Câu chẻ', 'C1', '___ I need is a good night\'s sleep.', ['What', 'That', 'It', 'Which'], 0, 'Câu chẻ dạng "What + mệnh đề + be + phần nhấn mạnh".'),
        q('cleft-sentences', 'Câu chẻ', 'C1', 'Nhấn mạnh "He lost his keys at the station": ___ he lost his keys.', ['It was at the station that', 'It was at the station which', 'There was at the station that', 'What was at the station that'], 0, 'Nhấn mạnh trạng ngữ nơi chốn dùng "It was + trạng ngữ + that".'),
        q('inversion', 'Đảo ngữ', 'C1', '___ have I seen such a beautiful view!', ['Never', 'Sometimes', 'Often', 'Always'], 0, 'Trạng từ phủ định (never, seldom, rarely) đứng đầu câu gây đảo ngữ.'),
        q('inversion', 'Đảo ngữ', 'C1', 'Only then ___ the truth.', ['did he understand', 'he understood', 'he did understand', 'understood he'], 0, 'Sau "Only then/Only later/Not until", trợ động từ đảo lên trước chủ ngữ.'),
        q('inversion', 'Đảo ngữ', 'C1', 'No sooner ___ he arrived than the phone rang.', ['had', 'did', 'has', 'was'], 0, 'Cấu trúc cố định: No sooner HAD + S + V3 + than + Past Simple.'),
        q('inversion-negative', 'Đảo ngữ phủ định', 'C1', 'Not until she called ___ the truth.', ['did I learn', 'I learned', 'I did learn', 'learned I'], 0, '"Not until + mệnh đề" kéo theo đảo ngữ ở mệnh đề chính.'),
        q('inversion-negative', 'Đảo ngữ phủ định', 'C2', 'Hardly ___ sat down when the bell rang.', ['had I', 'I had', 'did I', 'I did'], 0, 'Hardly/Scarcely + had + S + V3 + when + Past Simple.'),
        q('subjunctive', 'Thức giả định', 'C1', 'It is important that she ___ on time.', ['be', 'is', 'was', 'will be'], 0, 'Giả định sau tính từ mệnh lệnh (important, essential, vital) dùng V nguyên mẫu.'),
        q('subjunctive', 'Thức giả định', 'C1', 'I suggest that he ___ more carefully.', ['work', 'works', 'worked', 'working'], 0, 'Sau suggest/recommend/insist/demand + that + S + V nguyên mẫu (bỏ -s).'),
        q('subjunctive', 'Thức giả định', 'C1', 'The doctor insisted that the patient ___ in bed.', ['stay', 'stays', 'stayed', 'staying'], 0, 'Giả định hiện tại: động từ giữ nguyên mẫu cho mọi ngôi.'),
        q('subjunctive', 'Thức giả định', 'C2', 'He talks as though he ___ the boss.', ['were', 'is', 'was being', 'has been'], 0, '"as though/as if" trái thực tế → dùng "were" cho mọi ngôi.'),

        // ==================== TỪ VỰNG NGỮ PHÁP & LỖI THƯỜNG GẶP ====================
        q('phrasal-verbs', 'Cụm động từ', 'B1', 'Please ___ the lights before leaving.', ['turn off', 'turn on', 'turn up', 'turn into'], 0, 'turn off = tắt thiết bị.'),
        q('phrasal-verbs', 'Cụm động từ', 'B1', 'I need to ___ this problem before Monday.', ['figure out', 'figure in', 'figure on', 'figure over'], 0, 'figure out = hiểu ra, tìm ra lời giải.'),
        q('phrasal-verbs', 'Cụm động từ', 'B1', 'She had to ___ the meeting because she was ill.', ['call off', 'call on', 'call up', 'call in'], 0, 'call off = hủy bỏ.'),
        q('phrasal-verbs', 'Cụm động từ', 'B2', 'Chọn câu ĐÚNG với cụm động từ tách được:', ['Turn the radio off, please.', 'Turn off it, please.', 'Turn it off please them.', 'Off turn it, please.'], 0, 'Với cụm động từ tách được, đại từ (it/them) phải đứng GIỮA: turn it off.'),
        q('phrasal-verbs', 'Cụm động từ', 'B2', 'I ran ___ an old friend at the airport.', ['into', 'over', 'out', 'down'], 0, 'run into somebody = tình cờ gặp.'),
        q('phrasal-verbs', 'Cụm động từ', 'B2', 'We have ___ of milk.', ['run out', 'run off', 'run over', 'run up'], 0, 'run out of something = hết sạch thứ gì.'),
        q('collocations-pairs', 'Kết hợp từ', 'B1', 'I need to ___ a decision today.', ['make', 'do', 'take', 'get'], 0, 'Collocation: make a decision (không dùng "do a decision").'),
        q('collocations-pairs', 'Kết hợp từ', 'B1', 'She has to ___ her homework tonight.', ['do', 'make', 'take', 'give'], 0, 'Collocation: do homework / do the dishes / do exercise.'),
        q('collocations-pairs', 'Kết hợp từ', 'B2', 'They ___ a lot of progress this year.', ['made', 'did', 'took', 'got'], 0, 'Collocation: make progress.'),
        q('collocations-pairs', 'Kết hợp từ', 'B2', 'Can I ___ a photo of you?', ['take', 'make', 'do', 'get'], 0, 'Collocation: take a photo.'),

        q('fragments-run-ons', 'Câu què, câu dính', 'B1', 'Đâu là câu HOÀN CHỈNH?', ['The bus arrived late.', 'Because the bus arrived late.', 'Arriving late in the morning.', 'Which arrived late.'], 0, 'Câu hoàn chỉnh cần đủ chủ ngữ + động từ và đứng độc lập được.'),
        q('fragments-run-ons', 'Câu què, câu dính', 'B1', 'Câu nào bị lỗi "run-on" (câu dính)?', ['I was tired I went to bed.', 'I was tired, so I went to bed.', 'Because I was tired, I went to bed.', 'I was tired; I went to bed.'], 0, 'Hai mệnh đề độc lập không thể đứng cạnh nhau mà không có liên từ hoặc dấu chấm phẩy.'),
        q('punctuation-capitalization', 'Dấu câu', 'B1', 'Câu nào dùng dấu phẩy ĐÚNG?', ['When it rains, we stay inside.', 'When it rains we stay inside,', 'When, it rains we stay inside.', 'When it rains we, stay inside.'], 0, 'Mệnh đề phụ đứng TRƯỚC mệnh đề chính thì cần dấu phẩy ngăn cách.'),
        q('punctuation-capitalization', 'Dấu câu', 'B2', 'Câu nào dùng dấu nháy đơn (apostrophe) ĐÚNG?', ['The students\' books are on the desk. (nhiều học sinh)', 'The student\'s books are on the desk. (nhiều học sinh)', 'The students books\' are on the desk.', 'The students books are on the desk. (nhiều học sinh, sở hữu)'], 0, 'Danh từ số nhiều tận cùng -s chỉ thêm dấu nháy sau chữ s.'),
        q('punctuation-capitalization', 'Dấu câu', 'B2', 'Phân biệt: câu nào ĐÚNG?', ['It\'s raining and the dog lost its bone.', 'Its raining and the dog lost it\'s bone.', 'It\'s raining and the dog lost it\'s bone.', 'Its\' raining and the dog lost its bone.'], 0, 'it\'s = it is; its = của nó (sở hữu, không có dấu nháy).'),
        q('modifier-errors', 'Lỗi bổ nghĩa', 'B2', 'Câu nào KHÔNG mắc lỗi "dangling modifier"?', ['Walking to school, I saw a cat.', 'Walking to school, a cat was seen.', 'Walking to school, the cat appeared.', 'Walking to school, there was a cat.'], 0, 'Chủ ngữ của mệnh đề chính phải chính là người thực hiện hành động ở phân từ.'),
        q('modifier-errors', 'Lỗi bổ nghĩa', 'B2', 'Câu nào đặt "only" đúng chỗ để nói "chỉ mình tôi"?', ['Only I saw him yesterday.', 'I only saw him yesterday.', 'I saw only him yesterday.', 'I saw him only yesterday.'], 0, '"only" bổ nghĩa cho thành phần đứng ngay sau nó.'),
        q('pronoun-reference', 'Đại từ mơ hồ', 'B2', 'Câu nào có tham chiếu đại từ RÕ RÀNG?', ['Nam told Minh that Nam had passed.', 'Nam told Minh that he had passed.', 'Nam told Minh he passed it.', 'He told him that he passed.'], 0, 'Khi có hai người cùng giống, lặp lại tên rõ hơn là dùng đại từ mơ hồ.'),
        q('parallel-structure', 'Cấu trúc song song', 'B2', 'Liệt kê sở thích – câu nào giữ cấu trúc song song?', ['She likes swimming, running, and cycling.', 'She likes swimming, to run, and cycling.', 'She likes to swim, running, and cycle.', 'She likes swim, running, and to cycle.'], 0, 'Các thành phần liệt kê phải cùng dạng ngữ pháp.'),
        q('parallel-structure', 'Cấu trúc song song', 'C1', 'Mô tả yêu cầu công việc – câu nào giữ cấu trúc song song?', ['The job requires attention to detail and the ability to work fast.', 'The job requires attention to detail and to work fast.', 'The job requires attention to detail and working fast ability.', 'The job requires to pay attention and fast working.'], 0, 'Hai cụm danh từ nối bằng "and" phải cùng dạng danh từ.'),
        q('imperatives-requests', 'Câu mệnh lệnh & đề nghị', 'A2', '___ the window, please.', ['Open', 'You open', 'To open', 'Opening'], 0, 'Câu mệnh lệnh bắt đầu bằng động từ nguyên mẫu, không có chủ ngữ.'),
        q('politeness-indirectness', 'Lịch sự & gián tiếp', 'B2', 'Cách hỏi nào LỊCH SỰ nhất?', ['Would you mind opening the window?', 'Open the window.', 'You must open the window.', 'Why don\'t you just open it?'], 0, '"Would you mind + V-ing" là mẫu đề nghị lịch sự bậc cao.'),
        q('politeness-indirectness', 'Lịch sự & gián tiếp', 'B2', 'Trả lời "Would you mind opening the window?" mang nghĩa ĐỒNG Ý:', ['Not at all.', 'Yes, I would.', 'Yes, of course I mind.', 'Yes, please don\'t.'], 0, '"Would you mind...?" hỏi "bạn có phiền không", nên đồng ý là "Not at all / Of course not".'),
        q('exclamatory-sentences', 'Câu cảm thán', 'B1', '___ a beautiful day!', ['What', 'How', 'Such', 'So'], 0, 'What + (a/an) + adj + danh từ! / How + adj + S + V!'),
        q('exclamatory-sentences', 'Câu cảm thán', 'B1', '___ beautiful this place is!', ['How', 'What', 'What a', 'Such'], 0, 'How + tính từ + S + V!'),
        q('numerals', 'Số đếm & số thứ tự', 'A1', 'The ___ lesson is the most difficult.', ['fifth', 'five', 'fiveth', 'fifths'], 0, 'Số thứ tự của "five" là "fifth" (đổi ve → f + th).'),
        q('numerals', 'Số đếm & số thứ tự', 'A2', 'Cách đọc năm 1995 là:', ['nineteen ninety-five', 'one nine nine five', 'one thousand nine hundred ninety five', 'nineteen hundred ninety-five'], 0, 'Năm bốn chữ số thường đọc theo cặp: 19 – 95.'),
        q('numbers-dates', 'Số & ngày tháng', 'B1', 'Cách viết ngày kiểu Anh (BrE) đúng là:', ['5 March 2024', 'March 5 2024 (BrE)', '2024 March 5', '5 2024 March'], 0, 'Anh-Anh viết ngày trước tháng: 5 March 2024; Anh-Mỹ là March 5, 2024.'),
        q('grammar-registers', 'Văn phong', 'C1', 'Câu nào TRANG TRỌNG nhất?', ['The results indicate a significant improvement.', 'The results show things got way better.', 'Things look a lot better now.', 'It got better, which is nice.'], 0, 'Văn phong học thuật dùng động từ trung tính và tránh từ khẩu ngữ.'),
        q('academic-style-grammar', 'Văn phong học thuật', 'C1', 'Câu nào phù hợp văn viết học thuật nhất?', ['It can be argued that the policy is flawed.', 'I think the policy sucks.', 'The policy is bad, isn\'t it?', 'Everyone knows the policy is a mess.'], 0, 'Học thuật dùng cấu trúc rào đón bị động, tránh ngôi thứ nhất và cảm tính.'),
        q('hedges-boosters', 'Rào đón & nhấn mạnh', 'C1', 'Cách diễn đạt nào THẬN TRỌNG nhất?', ['The data suggest that stress may affect sleep.', 'The data prove stress destroys sleep.', 'Stress always ruins sleep.', 'Stress definitely ruins sleep.'], 0, 'suggest + may là cặp rào đón điển hình trong văn học thuật.'),
        q('gender-neutral-grammar', 'Ngữ pháp trung tính', 'B2', 'Cách diễn đạt trung tính giới nhất là:', ['Each employee should update their profile.', 'Each employee should update his profile.', 'Each employee should update his or her profiles.', 'Each employees should update their profile.'], 0, 'Tiếng Anh hiện đại chấp nhận "their" số ít làm đại từ trung tính.')
    ];
})();

if (typeof window !== 'undefined') {
    window.grammarExerciseBank = grammarExerciseBank;
}
