// Common irregular verbs for quick reference
window.irregularVerbs = [
    { base: 'arise', past: 'arose', participle: 'arisen', meaning: 'phát sinh, nảy sinh' },
    { base: 'awake', past: 'awoke', participle: 'awoken', meaning: 'thức dậy' },
    { base: 'be', past: 'was/were', participle: 'been', meaning: 'thì, là, ở' },
    { base: 'bear', past: 'bore', participle: 'borne/born', meaning: 'chịu đựng, mang; sinh ra' },
    { base: 'beat', past: 'beat', participle: 'beaten', meaning: 'đánh, đập, thắng' },
    { base: 'become', past: 'became', participle: 'become', meaning: 'trở nên' },
    { base: 'begin', past: 'began', participle: 'begun', meaning: 'bắt đầu' },
    { base: 'bend', past: 'bent', participle: 'bent', meaning: 'uốn cong' },
    { base: 'bet', past: 'bet', participle: 'bet', meaning: 'đánh cược' },
    { base: 'bind', past: 'bound', participle: 'bound', meaning: 'buộc, ràng buộc' },
    { base: 'bite', past: 'bit', participle: 'bitten', meaning: 'cắn' },
    { base: 'bleed', past: 'bled', participle: 'bled', meaning: 'chảy máu' },
    { base: 'blow', past: 'blew', participle: 'blown', meaning: 'thổi' },
    { base: 'break', past: 'broke', participle: 'broken', meaning: 'làm vỡ, phá vỡ' },
    { base: 'breed', past: 'bred', participle: 'bred', meaning: 'nuôi, gây giống' },
    { base: 'bring', past: 'brought', participle: 'brought', meaning: 'mang đến' },
    { base: 'broadcast', past: 'broadcast', participle: 'broadcast', meaning: 'phát sóng' },
    { base: 'build', past: 'built', participle: 'built', meaning: 'xây dựng' },
    { base: 'burn', past: 'burnt/burned', participle: 'burnt/burned', meaning: 'đốt, cháy' },
    { base: 'buy', past: 'bought', participle: 'bought', meaning: 'mua' },
    { base: 'catch', past: 'caught', participle: 'caught', meaning: 'bắt, chộp' },
    { base: 'choose', past: 'chose', participle: 'chosen', meaning: 'chọn' },
    { base: 'come', past: 'came', participle: 'come', meaning: 'đến' },
    { base: 'cost', past: 'cost', participle: 'cost', meaning: 'có giá, tiêu tốn' },
    { base: 'creep', past: 'crept', participle: 'crept', meaning: 'bò, rón rén' },
    { base: 'cut', past: 'cut', participle: 'cut', meaning: 'cắt' },
    { base: 'deal', past: 'dealt', participle: 'dealt', meaning: 'xử lý, giao dịch' },
    { base: 'dig', past: 'dug', participle: 'dug', meaning: 'đào' },
    { base: 'do', past: 'did', participle: 'done', meaning: 'làm' },
    { base: 'draw', past: 'drew', participle: 'drawn', meaning: 'vẽ, kéo' },
    { base: 'dream', past: 'dreamt/dreamed', participle: 'dreamt/dreamed', meaning: 'mơ' },
    { base: 'drink', past: 'drank', participle: 'drunk', meaning: 'uống' },
    { base: 'drive', past: 'drove', participle: 'driven', meaning: 'lái xe, thúc đẩy' },
    { base: 'eat', past: 'ate', participle: 'eaten', meaning: 'ăn' },
    { base: 'fall', past: 'fell', participle: 'fallen', meaning: 'ngã, rơi' },
    { base: 'feed', past: 'fed', participle: 'fed', meaning: 'cho ăn, cấp dữ liệu' },
    { base: 'feel', past: 'felt', participle: 'felt', meaning: 'cảm thấy' },
    { base: 'fight', past: 'fought', participle: 'fought', meaning: 'chiến đấu, tranh đấu' },
    { base: 'find', past: 'found', participle: 'found', meaning: 'tìm thấy' },
    { base: 'fit', past: 'fit/fitted', participle: 'fit/fitted', meaning: 'vừa, phù hợp' },
    { base: 'flee', past: 'fled', participle: 'fled', meaning: 'chạy trốn' },
    { base: 'fly', past: 'flew', participle: 'flown', meaning: 'bay' },
    { base: 'forbid', past: 'forbade', participle: 'forbidden', meaning: 'cấm' },
    { base: 'forget', past: 'forgot', participle: 'forgotten', meaning: 'quên' },
    { base: 'forgive', past: 'forgave', participle: 'forgiven', meaning: 'tha thứ' },
    { base: 'freeze', past: 'froze', participle: 'frozen', meaning: 'đóng băng' },
    { base: 'get', past: 'got', participle: 'got/gotten', meaning: 'có được, trở nên, nhận' },
    { base: 'give', past: 'gave', participle: 'given', meaning: 'đưa, cho' },
    { base: 'go', past: 'went', participle: 'gone', meaning: 'đi' },
    { base: 'grow', past: 'grew', participle: 'grown', meaning: 'lớn lên, phát triển, trồng' },
    { base: 'hang', past: 'hung', participle: 'hung', meaning: 'treo' },
    { base: 'have', past: 'had', participle: 'had', meaning: 'có' },
    { base: 'hear', past: 'heard', participle: 'heard', meaning: 'nghe' },
    { base: 'hide', past: 'hid', participle: 'hidden', meaning: 'ẩn, giấu' },
    { base: 'hit', past: 'hit', participle: 'hit', meaning: 'đánh, va chạm' },
    { base: 'hold', past: 'held', participle: 'held', meaning: 'giữ, cầm, tổ chức' },
    { base: 'hurt', past: 'hurt', participle: 'hurt', meaning: 'làm đau, bị đau' },
    { base: 'keep', past: 'kept', participle: 'kept', meaning: 'giữ' },
    { base: 'kneel', past: 'knelt', participle: 'knelt', meaning: 'quỳ' },
    { base: 'know', past: 'knew', participle: 'known', meaning: 'biết' },
    { base: 'lay', past: 'laid', participle: 'laid', meaning: 'đặt, để, đẻ trứng' },
    { base: 'lead', past: 'led', participle: 'led', meaning: 'dẫn dắt' },
    { base: 'lean', past: 'leant/leaned', participle: 'leant/leaned', meaning: 'nghiêng, tựa' },
    { base: 'leap', past: 'leapt/leaped', participle: 'leapt/leaped', meaning: 'nhảy vọt' },
    { base: 'learn', past: 'learnt/learned', participle: 'learnt/learned', meaning: 'học' },
    { base: 'leave', past: 'left', participle: 'left', meaning: 'rời đi, để lại' },
    { base: 'lend', past: 'lent', participle: 'lent', meaning: 'cho mượn' },
    { base: 'let', past: 'let', participle: 'let', meaning: 'cho phép, để cho' },
    { base: 'lie', past: 'lay', participle: 'lain', meaning: 'nằm' },
    { base: 'light', past: 'lit/lighted', participle: 'lit/lighted', meaning: 'thắp sáng' },
    { base: 'lose', past: 'lost', participle: 'lost', meaning: 'mất, thua' },
    { base: 'make', past: 'made', participle: 'made', meaning: 'làm, tạo ra' },
    { base: 'mean', past: 'meant', participle: 'meant', meaning: 'có nghĩa, dự định' },
    { base: 'meet', past: 'met', participle: 'met', meaning: 'gặp' },
    { base: 'pay', past: 'paid', participle: 'paid', meaning: 'trả tiền, trả giá' },
    { base: 'prove', past: 'proved', participle: 'proven/proved', meaning: 'chứng minh' },
    { base: 'put', past: 'put', participle: 'put', meaning: 'đặt, để' },
    { base: 'read', past: 'read', participle: 'read', meaning: 'đọc' },
    { base: 'ride', past: 'rode', participle: 'ridden', meaning: 'cưỡi, đi' },
    { base: 'ring', past: 'rang', participle: 'rung', meaning: 'rung, reo' },
    { base: 'rise', past: 'rose', participle: 'risen', meaning: 'tăng lên, mọc lên' },
    { base: 'run', past: 'ran', participle: 'run', meaning: 'chạy, vận hành' },
    { base: 'say', past: 'said', participle: 'said', meaning: 'nói' },
    { base: 'see', past: 'saw', participle: 'seen', meaning: 'thấy' },
    { base: 'seek', past: 'sought', participle: 'sought', meaning: 'tìm kiếm' },
    { base: 'sell', past: 'sold', participle: 'sold', meaning: 'bán' },
    { base: 'send', past: 'sent', participle: 'sent', meaning: 'gửi' },
    { base: 'set', past: 'set', participle: 'set', meaning: 'đặt, thiết lập' },
    { base: 'shake', past: 'shook', participle: 'shaken', meaning: 'lắc' },
    { base: 'shine', past: 'shone', participle: 'shone', meaning: 'chiếu sáng, tỏa sáng' },
    { base: 'shoot', past: 'shot', participle: 'shot', meaning: 'bắn, chụp ảnh/quay phim' },
    { base: 'show', past: 'showed', participle: 'shown/showed', meaning: 'cho thấy, trình diễn' },
    { base: 'shut', past: 'shut', participle: 'shut', meaning: 'đóng lại' },
    { base: 'sing', past: 'sang', participle: 'sung', meaning: 'hát' },
    { base: 'sink', past: 'sank', participle: 'sunk', meaning: 'chìm' },
    { base: 'sit', past: 'sat', participle: 'sat', meaning: 'ngồi' },
    { base: 'sleep', past: 'slept', participle: 'slept', meaning: 'ngủ' },
    { base: 'slide', past: 'slid', participle: 'slid', meaning: 'trượt' },
    { base: 'speak', past: 'spoke', participle: 'spoken', meaning: 'nói' },
    { base: 'spend', past: 'spent', participle: 'spent', meaning: 'tiêu, dành thời gian' },
    { base: 'spin', past: 'spun', participle: 'spun', meaning: 'quay, xoay' },
    { base: 'spread', past: 'spread', participle: 'spread', meaning: 'lan rộng, trải ra' },
    { base: 'stand', past: 'stood', participle: 'stood', meaning: 'đứng' },
    { base: 'steal', past: 'stole', participle: 'stolen', meaning: 'ăn cắp' },
    { base: 'stick', past: 'stuck', participle: 'stuck', meaning: 'dính, ghim, gắn' },
    { base: 'sting', past: 'stung', participle: 'stung', meaning: 'đốt, châm chích' },
    { base: 'strike', past: 'struck', participle: 'struck', meaning: 'đánh, đình công, nảy ra' },
    { base: 'swear', past: 'swore', participle: 'sworn', meaning: 'thề, chửi thề' },
    { base: 'sweep', past: 'swept', participle: 'swept', meaning: 'quét' },
    { base: 'swim', past: 'swam', participle: 'swum', meaning: 'bơi' },
    { base: 'take', past: 'took', participle: 'taken', meaning: 'lấy, mang, dành' },
    { base: 'teach', past: 'taught', participle: 'taught', meaning: 'dạy' },
    { base: 'tear', past: 'tore', participle: 'torn', meaning: 'xé' },
    { base: 'tell', past: 'told', participle: 'told', meaning: 'kể, bảo' },
    { base: 'think', past: 'thought', participle: 'thought', meaning: 'nghĩ' },
    { base: 'throw', past: 'threw', participle: 'thrown', meaning: 'ném' },
    { base: 'understand', past: 'understood', participle: 'understood', meaning: 'hiểu' },
    { base: 'wake', past: 'woke', participle: 'woken', meaning: 'đánh thức, thức dậy' },
    { base: 'wear', past: 'wore', participle: 'worn', meaning: 'mặc, đeo' },
    { base: 'weep', past: 'wept', participle: 'wept', meaning: 'khóc' },
    { base: 'win', past: 'won', participle: 'won', meaning: 'thắng' },
    { base: 'write', past: 'wrote', participle: 'written', meaning: 'viết' }
];
