// Irregular verbs — bảng tra cứu đầy đủ, phân nhóm theo cách biến đổi V1/V2/V3.
// group: "same" (V1=V2=V3) | "pastpart" (V2=V3, khác V1) | "basepart" (V1=V3, khác V2)
//        | "other" (biến đổi nguyên âm / đuôi -en / hoàn toàn khác nhau, gồm be, go...)
// tier:  "core" (cần thuộc trước) | "derived" (từ ghép tiền tố của một động từ gốc) | "extra" (ít dùng, văn học)
const irregularVerbGroups = {
    same: { label: 'Cả 3 dạng giống nhau', short: 'V1=V2=V3', example: 'cut – cut – cut' },
    pastpart: { label: 'Quá khứ = Phân từ', short: 'V2=V3', example: 'keep – kept – kept' },
    basepart: { label: 'Nguyên mẫu = Phân từ', short: 'V1=V3', example: 'come – came – come' },
    other: { label: 'Biến đổi khác (nguyên âm / -en / be, go...)', short: 'khác nhau', example: 'write – wrote – written' }
};

const irregularVerbs = [
    { base: 'bet', past: 'bet', participle: 'bet', meaning: 'đánh cược', group: 'same', tier: 'core' },
    { base: 'bid', past: 'bid', participle: 'bid', meaning: 'ra giá, đấu thầu', group: 'same', tier: 'core' },
    { base: 'broadcast', past: 'broadcast', participle: 'broadcast', meaning: 'phát sóng', group: 'same', tier: 'core' },
    { base: 'burst', past: 'burst', participle: 'burst', meaning: 'nổ, vỡ tung', group: 'same', tier: 'core' },
    { base: 'cast', past: 'cast', participle: 'cast', meaning: 'ném, đúc, chọn vai', group: 'same', tier: 'core' },
    { base: 'cost', past: 'cost', participle: 'cost', meaning: 'có giá, tốn (chi phí)', group: 'same', tier: 'core' },
    { base: 'cut', past: 'cut', participle: 'cut', meaning: 'cắt', group: 'same', tier: 'core' },
    { base: 'fit', past: 'fit/fitted', participle: 'fit/fitted', meaning: 'vừa vặn, phù hợp', group: 'same', tier: 'core' },
    { base: 'hit', past: 'hit', participle: 'hit', meaning: 'đánh, va chạm', group: 'same', tier: 'core' },
    { base: 'hurt', past: 'hurt', participle: 'hurt', meaning: 'làm đau, gây hại', group: 'same', tier: 'core' },
    { base: 'knit', past: 'knit/knitted', participle: 'knit/knitted', meaning: 'đan (len)', group: 'same', tier: 'core' },
    { base: 'let', past: 'let', participle: 'let', meaning: 'để cho, cho phép', group: 'same', tier: 'core' },
    { base: 'put', past: 'put', participle: 'put', meaning: 'đặt, để', group: 'same', tier: 'core' },
    { base: 'quit', past: 'quit/quitted', participle: 'quit/quitted', meaning: 'bỏ, thôi', group: 'same', tier: 'core' },
    { base: 'read', past: 'read', participle: 'read', meaning: 'đọc (phát âm 3 dạng khác nhau: /riːd/-/red/-/red/)', group: 'same', tier: 'core' },
    { base: 'rid', past: 'rid', participle: 'rid', meaning: 'loại bỏ, giải thoát khỏi', group: 'same', tier: 'core' },
    { base: 'set', past: 'set', participle: 'set', meaning: 'đặt, thiết lập', group: 'same', tier: 'core' },
    { base: 'shed', past: 'shed', participle: 'shed', meaning: 'rụng, tuôn (nước mắt, máu)', group: 'same', tier: 'core' },
    { base: 'shut', past: 'shut', participle: 'shut', meaning: 'đóng lại', group: 'same', tier: 'core' },
    { base: 'slit', past: 'slit', participle: 'slit', meaning: 'rạch, khía', group: 'same', tier: 'core' },
    { base: 'split', past: 'split', participle: 'split', meaning: 'chia tách, tách ra', group: 'same', tier: 'core' },
    { base: 'spread', past: 'spread', participle: 'spread', meaning: 'trải ra, lan rộng', group: 'same', tier: 'core' },
    { base: 'thrust', past: 'thrust', participle: 'thrust', meaning: 'thọc, đẩy mạnh', group: 'same', tier: 'core' },
    { base: 'upset', past: 'upset', participle: 'upset', meaning: 'làm khó chịu, làm đảo lộn', group: 'same', tier: 'core' },
    { base: 'wet', past: 'wet/wetted', participle: 'wet/wetted', meaning: 'làm ướt', group: 'same', tier: 'core' },
    { base: 'forecast', past: 'forecast/forecasted', participle: 'forecast/forecasted', meaning: 'dự báo', group: 'same', tier: 'derived', note: 'gốc: cast' },
    { base: 'input', past: 'input/inputted', participle: 'input/inputted', meaning: 'nhập (dữ liệu)', group: 'same', tier: 'derived', note: 'gốc: put' },
    { base: 'offset', past: 'offset', participle: 'offset', meaning: 'bù trừ, bù đắp', group: 'same', tier: 'derived', note: 'gốc: set' },
    { base: 'outbid', past: 'outbid', participle: 'outbid', meaning: 'trả giá cao hơn', group: 'same', tier: 'derived', note: 'gốc: bid' },
    { base: 'output', past: 'output/outputted', participle: 'output/outputted', meaning: 'xuất (dữ liệu)', group: 'same', tier: 'derived', note: 'gốc: put' },
    { base: 'preset', past: 'preset', participle: 'preset', meaning: 'cài đặt sẵn', group: 'same', tier: 'derived', note: 'gốc: set' },
    { base: 'rebroadcast', past: 'rebroadcast', participle: 'rebroadcast', meaning: 'phát sóng lại', group: 'same', tier: 'derived', note: 'gốc: broadcast' },
    { base: 'recast', past: 'recast', participle: 'recast', meaning: 'đúc lại, chọn lại vai diễn', group: 'same', tier: 'derived', note: 'gốc: cast' },
    { base: 'recut', past: 'recut', participle: 'recut', meaning: 'cắt lại', group: 'same', tier: 'derived', note: 'gốc: cut' },
    { base: 'reset', past: 'reset', participle: 'reset', meaning: 'đặt lại, thiết lập lại', group: 'same', tier: 'derived', note: 'gốc: set' },
    { base: 'misread', past: 'misread', participle: 'misread', meaning: 'đọc sai, hiểu sai', group: 'same', tier: 'derived', note: 'gốc: read' },
    { base: 'proofread', past: 'proofread', participle: 'proofread', meaning: 'đọc soát lỗi bản in', group: 'same', tier: 'derived', note: 'gốc: read' },
    { base: 'reread', past: 'reread', participle: 'reread', meaning: 'đọc lại', group: 'same', tier: 'derived', note: 'gốc: read' },
    { base: 'undercut', past: 'undercut', participle: 'undercut', meaning: 'bán phá giá, chơi xấu', group: 'same', tier: 'derived', note: 'gốc: cut' },
    { base: 'bend', past: 'bent', participle: 'bent', meaning: 'uốn cong, bẻ cong', group: 'pastpart', tier: 'core' },
    { base: 'bind', past: 'bound', participle: 'bound', meaning: 'buộc, ràng buộc', group: 'pastpart', tier: 'core' },
    { base: 'bleed', past: 'bled', participle: 'bled', meaning: 'chảy máu', group: 'pastpart', tier: 'core' },
    { base: 'breed', past: 'bred', participle: 'bred', meaning: 'nuôi, gây giống', group: 'pastpart', tier: 'core' },
    { base: 'bring', past: 'brought', participle: 'brought', meaning: 'mang đến', group: 'pastpart', tier: 'core' },
    { base: 'build', past: 'built', participle: 'built', meaning: 'xây dựng', group: 'pastpart', tier: 'core' },
    { base: 'burn', past: 'burnt/burned', participle: 'burnt/burned', meaning: 'đốt, cháy', group: 'pastpart', tier: 'core' },
    { base: 'buy', past: 'bought', participle: 'bought', meaning: 'mua', group: 'pastpart', tier: 'core' },
    { base: 'catch', past: 'caught', participle: 'caught', meaning: 'bắt, chộp, bắt kịp', group: 'pastpart', tier: 'core' },
    { base: 'cling', past: 'clung', participle: 'clung', meaning: 'bám chặt, bám víu', group: 'pastpart', tier: 'core' },
    { base: 'creep', past: 'crept', participle: 'crept', meaning: 'bò, rón rén', group: 'pastpart', tier: 'core' },
    { base: 'deal', past: 'dealt', participle: 'dealt', meaning: 'xử lý, giao dịch, chia bài', group: 'pastpart', tier: 'core' },
    { base: 'dig', past: 'dug', participle: 'dug', meaning: 'đào', group: 'pastpart', tier: 'core' },
    { base: 'dream', past: 'dreamt/dreamed', participle: 'dreamt/dreamed', meaning: 'mơ, mơ ước', group: 'pastpart', tier: 'core' },
    { base: 'feed', past: 'fed', participle: 'fed', meaning: 'cho ăn, nuôi', group: 'pastpart', tier: 'core' },
    { base: 'feel', past: 'felt', participle: 'felt', meaning: 'cảm thấy', group: 'pastpart', tier: 'core' },
    { base: 'fight', past: 'fought', participle: 'fought', meaning: 'chiến đấu, tranh đấu', group: 'pastpart', tier: 'core' },
    { base: 'find', past: 'found', participle: 'found', meaning: 'tìm thấy', group: 'pastpart', tier: 'core' },
    { base: 'flee', past: 'fled', participle: 'fled', meaning: 'chạy trốn', group: 'pastpart', tier: 'core' },
    { base: 'fling', past: 'flung', participle: 'flung', meaning: 'ném mạnh, quăng', group: 'pastpart', tier: 'core' },
    { base: 'grind', past: 'ground', participle: 'ground', meaning: 'nghiền, xay, mài', group: 'pastpart', tier: 'core' },
    { base: 'hang', past: 'hung', participle: 'hung', meaning: 'treo (nghĩa "xử tử" thì chia đều: hanged/hanged)', group: 'pastpart', tier: 'core' },
    { base: 'have', past: 'had', participle: 'had', meaning: 'có', group: 'pastpart', tier: 'core' },
    { base: 'hear', past: 'heard', participle: 'heard', meaning: 'nghe', group: 'pastpart', tier: 'core' },
    { base: 'hold', past: 'held', participle: 'held', meaning: 'giữ, cầm, tổ chức', group: 'pastpart', tier: 'core' },
    { base: 'keep', past: 'kept', participle: 'kept', meaning: 'giữ', group: 'pastpart', tier: 'core' },
    { base: 'kneel', past: 'knelt/kneeled', participle: 'knelt/kneeled', meaning: 'quỳ', group: 'pastpart', tier: 'core' },
    { base: 'lay', past: 'laid', participle: 'laid', meaning: 'đặt, để, đẻ trứng', group: 'pastpart', tier: 'core' },
    { base: 'lead', past: 'led', participle: 'led', meaning: 'dẫn dắt, lãnh đạo', group: 'pastpart', tier: 'core' },
    { base: 'lean', past: 'leant/leaned', participle: 'leant/leaned', meaning: 'nghiêng, tựa vào', group: 'pastpart', tier: 'core' },
    { base: 'leap', past: 'leapt/leaped', participle: 'leapt/leaped', meaning: 'nhảy vọt', group: 'pastpart', tier: 'core' },
    { base: 'learn', past: 'learnt/learned', participle: 'learnt/learned', meaning: 'học', group: 'pastpart', tier: 'core' },
    { base: 'leave', past: 'left', participle: 'left', meaning: 'rời đi, để lại', group: 'pastpart', tier: 'core' },
    { base: 'lend', past: 'lent', participle: 'lent', meaning: 'cho mượn', group: 'pastpart', tier: 'core' },
    { base: 'light', past: 'lit/lighted', participle: 'lit/lighted', meaning: 'thắp sáng, đốt', group: 'pastpart', tier: 'core' },
    { base: 'lose', past: 'lost', participle: 'lost', meaning: 'mất, thua', group: 'pastpart', tier: 'core' },
    { base: 'make', past: 'made', participle: 'made', meaning: 'làm, tạo ra', group: 'pastpart', tier: 'core' },
    { base: 'mean', past: 'meant', participle: 'meant', meaning: 'có nghĩa, dự định', group: 'pastpart', tier: 'core' },
    { base: 'meet', past: 'met', participle: 'met', meaning: 'gặp', group: 'pastpart', tier: 'core' },
    { base: 'pay', past: 'paid', participle: 'paid', meaning: 'trả tiền, trả giá', group: 'pastpart', tier: 'core' },
    { base: 'say', past: 'said', participle: 'said', meaning: 'nói', group: 'pastpart', tier: 'core' },
    { base: 'seek', past: 'sought', participle: 'sought', meaning: 'tìm kiếm', group: 'pastpart', tier: 'core' },
    { base: 'sell', past: 'sold', participle: 'sold', meaning: 'bán', group: 'pastpart', tier: 'core' },
    { base: 'send', past: 'sent', participle: 'sent', meaning: 'gửi', group: 'pastpart', tier: 'core' },
    { base: 'shine', past: 'shone', participle: 'shone', meaning: 'chiếu sáng, tỏa sáng', group: 'pastpart', tier: 'core' },
    { base: 'shoot', past: 'shot', participle: 'shot', meaning: 'bắn, chụp/quay (ảnh, phim)', group: 'pastpart', tier: 'core' },
    { base: 'sit', past: 'sat', participle: 'sat', meaning: 'ngồi', group: 'pastpart', tier: 'core' },
    { base: 'sleep', past: 'slept', participle: 'slept', meaning: 'ngủ', group: 'pastpart', tier: 'core' },
    { base: 'slide', past: 'slid', participle: 'slid', meaning: 'trượt', group: 'pastpart', tier: 'core' },
    { base: 'sling', past: 'slung', participle: 'slung', meaning: 'ném, quăng, đeo (túi)', group: 'pastpart', tier: 'core' },
    { base: 'slink', past: 'slunk', participle: 'slunk', meaning: 'lẻn đi, đi lén lút', group: 'pastpart', tier: 'extra' },
    { base: 'smell', past: 'smelt/smelled', participle: 'smelt/smelled', meaning: 'ngửi, có mùi', group: 'pastpart', tier: 'core' },
    { base: 'speed', past: 'sped/speeded', participle: 'sped/speeded', meaning: 'chạy nhanh, tăng tốc', group: 'pastpart', tier: 'core' },
    { base: 'spell', past: 'spelt/spelled', participle: 'spelt/spelled', meaning: 'đánh vần', group: 'pastpart', tier: 'core' },
    { base: 'spend', past: 'spent', participle: 'spent', meaning: 'tiêu (tiền), dành (thời gian)', group: 'pastpart', tier: 'core' },
    { base: 'spill', past: 'spilt/spilled', participle: 'spilt/spilled', meaning: 'làm đổ, tràn ra', group: 'pastpart', tier: 'core' },
    { base: 'spin', past: 'spun', participle: 'spun', meaning: 'quay, xoay tròn', group: 'pastpart', tier: 'core' },
    { base: 'spoil', past: 'spoilt/spoiled', participle: 'spoilt/spoiled', meaning: 'làm hỏng, nuông chiều', group: 'pastpart', tier: 'core' },
    { base: 'stand', past: 'stood', participle: 'stood', meaning: 'đứng', group: 'pastpart', tier: 'core' },
    { base: 'stick', past: 'stuck', participle: 'stuck', meaning: 'dính, ghim, gắn', group: 'pastpart', tier: 'core' },
    { base: 'sting', past: 'stung', participle: 'stung', meaning: 'đốt, châm chích', group: 'pastpart', tier: 'core' },
    { base: 'strike', past: 'struck', participle: 'struck', meaning: 'đánh, đình công, nảy ra (ý)', group: 'pastpart', tier: 'core' },
    { base: 'string', past: 'strung', participle: 'strung', meaning: 'xâu chuỗi, mắc dây', group: 'pastpart', tier: 'extra' },
    { base: 'sweep', past: 'swept', participle: 'swept', meaning: 'quét', group: 'pastpart', tier: 'core' },
    { base: 'swing', past: 'swung', participle: 'swung', meaning: 'đung đưa, xoay', group: 'pastpart', tier: 'core' },
    { base: 'teach', past: 'taught', participle: 'taught', meaning: 'dạy', group: 'pastpart', tier: 'core' },
    { base: 'tell', past: 'told', participle: 'told', meaning: 'kể, bảo', group: 'pastpart', tier: 'core' },
    { base: 'think', past: 'thought', participle: 'thought', meaning: 'nghĩ', group: 'pastpart', tier: 'core' },
    { base: 'understand', past: 'understood', participle: 'understood', meaning: 'hiểu', group: 'pastpart', tier: 'core' },
    { base: 'weep', past: 'wept', participle: 'wept', meaning: 'khóc', group: 'pastpart', tier: 'core' },
    { base: 'win', past: 'won', participle: 'won', meaning: 'thắng', group: 'pastpart', tier: 'core' },
    { base: 'wind', past: 'wound', participle: 'wound', meaning: 'quấn, lên dây cót, uốn khúc', group: 'pastpart', tier: 'core' },
    { base: 'wring', past: 'wrung', participle: 'wrung', meaning: 'vặn, siết chặt', group: 'pastpart', tier: 'extra' },
    { base: 'mislay', past: 'mislaid', participle: 'mislaid', meaning: 'để thất lạc', group: 'pastpart', tier: 'derived', note: 'gốc: lay' },
    { base: 'mislead', past: 'misled', participle: 'misled', meaning: 'đánh lừa, dẫn sai đường', group: 'pastpart', tier: 'derived', note: 'gốc: lead' },
    { base: 'mishear', past: 'misheard', participle: 'misheard', meaning: 'nghe nhầm', group: 'pastpart', tier: 'derived', note: 'gốc: hear' },
    { base: 'misspell', past: 'misspelt/misspelled', participle: 'misspelt/misspelled', meaning: 'viết sai chính tả', group: 'pastpart', tier: 'derived', note: 'gốc: spell' },
    { base: 'misspend', past: 'misspent', participle: 'misspent', meaning: 'tiêu phí, dùng sai mục đích', group: 'pastpart', tier: 'derived', note: 'gốc: spend' },
    { base: 'misunderstand', past: 'misunderstood', participle: 'misunderstood', meaning: 'hiểu nhầm', group: 'pastpart', tier: 'derived', note: 'gốc: understand' },
    { base: 'overbuild', past: 'overbuilt', participle: 'overbuilt', meaning: 'xây dựng quá mức', group: 'pastpart', tier: 'derived', note: 'gốc: build' },
    { base: 'overbuy', past: 'overbought', participle: 'overbought', meaning: 'mua quá nhiều', group: 'pastpart', tier: 'derived', note: 'gốc: buy' },
    { base: 'overfeed', past: 'overfed', participle: 'overfed', meaning: 'cho ăn quá mức', group: 'pastpart', tier: 'derived', note: 'gốc: feed' },
    { base: 'overhang', past: 'overhung', participle: 'overhung', meaning: 'nhô ra, treo lơ lửng trên', group: 'pastpart', tier: 'derived', note: 'gốc: hang' },
    { base: 'overhear', past: 'overheard', participle: 'overheard', meaning: 'nghe lỏm, nghe trộm', group: 'pastpart', tier: 'derived', note: 'gốc: hear' },
    { base: 'overpay', past: 'overpaid', participle: 'overpaid', meaning: 'trả quá nhiều tiền', group: 'pastpart', tier: 'derived', note: 'gốc: pay' },
    { base: 'oversleep', past: 'overslept', participle: 'overslept', meaning: 'ngủ quên', group: 'pastpart', tier: 'derived', note: 'gốc: sleep' },
    { base: 'overspend', past: 'overspent', participle: 'overspent', meaning: 'chi tiêu quá mức', group: 'pastpart', tier: 'derived', note: 'gốc: spend' },
    { base: 'overthink', past: 'overthought', participle: 'overthought', meaning: 'suy nghĩ quá nhiều', group: 'pastpart', tier: 'derived', note: 'gốc: think' },
    { base: 'prepay', past: 'prepaid', participle: 'prepaid', meaning: 'trả trước', group: 'pastpart', tier: 'derived', note: 'gốc: pay' },
    { base: 'rebind', past: 'rebound', participle: 'rebound', meaning: 'buộc lại, đóng (sách) lại', group: 'pastpart', tier: 'derived', note: 'gốc: bind' },
    { base: 'rebuild', past: 'rebuilt', participle: 'rebuilt', meaning: 'xây dựng lại', group: 'pastpart', tier: 'derived', note: 'gốc: build' },
    { base: 'rehang', past: 'rehung', participle: 'rehung', meaning: 'treo lại', group: 'pastpart', tier: 'derived', note: 'gốc: hang' },
    { base: 'relearn', past: 'relearnt/relearned', participle: 'relearnt/relearned', meaning: 'học lại', group: 'pastpart', tier: 'derived', note: 'gốc: learn' },
    { base: 'relight', past: 'relit', participle: 'relit', meaning: 'thắp sáng lại', group: 'pastpart', tier: 'derived', note: 'gốc: light' },
    { base: 'repay', past: 'repaid', participle: 'repaid', meaning: 'hoàn trả', group: 'pastpart', tier: 'derived', note: 'gốc: pay' },
    { base: 'resell', past: 'resold', participle: 'resold', meaning: 'bán lại', group: 'pastpart', tier: 'derived', note: 'gốc: sell' },
    { base: 'resend', past: 'resent', participle: 'resent', meaning: 'gửi lại', group: 'pastpart', tier: 'derived', note: 'gốc: send' },
    { base: 'retell', past: 'retold', participle: 'retold', meaning: 'kể lại', group: 'pastpart', tier: 'derived', note: 'gốc: tell' },
    { base: 'rethink', past: 'rethought', participle: 'rethought', meaning: 'suy nghĩ lại', group: 'pastpart', tier: 'derived', note: 'gốc: think' },
    { base: 'rewind', past: 'rewound', participle: 'rewound', meaning: 'tua lại, quấn lại', group: 'pastpart', tier: 'derived', note: 'gốc: wind' },
    { base: 'unbend', past: 'unbent', participle: 'unbent', meaning: 'làm thẳng lại, bớt cứng nhắc', group: 'pastpart', tier: 'derived', note: 'gốc: bend' },
    { base: 'unbind', past: 'unbound', participle: 'unbound', meaning: 'tháo ra, cởi trói', group: 'pastpart', tier: 'derived', note: 'gốc: bind' },
    { base: 'underfeed', past: 'underfed', participle: 'underfed', meaning: 'cho ăn thiếu', group: 'pastpart', tier: 'derived', note: 'gốc: feed' },
    { base: 'unwind', past: 'unwound', participle: 'unwound', meaning: 'tháo ra, thư giãn', group: 'pastpart', tier: 'derived', note: 'gốc: wind' },
    { base: 'uphold', past: 'upheld', participle: 'upheld', meaning: 'giữ vững, ủng hộ', group: 'pastpart', tier: 'derived', note: 'gốc: hold' },
    { base: 'withhold', past: 'withheld', participle: 'withheld', meaning: 'giữ lại, từ chối cho', group: 'pastpart', tier: 'derived', note: 'gốc: hold' },
    { base: 'withstand', past: 'withstood', participle: 'withstood', meaning: 'chống chịu, chịu đựng', group: 'pastpart', tier: 'derived', note: 'gốc: stand' },
    { base: 'outfight', past: 'outfought', participle: 'outfought', meaning: 'đánh giỏi hơn', group: 'pastpart', tier: 'derived', note: 'gốc: fight' },
    { base: 'outsell', past: 'outsold', participle: 'outsold', meaning: 'bán chạy hơn', group: 'pastpart', tier: 'derived', note: 'gốc: sell' },
    { base: 'outshine', past: 'outshone', participle: 'outshone', meaning: 'vượt trội hơn, sáng hơn', group: 'pastpart', tier: 'derived', note: 'gốc: shine' },
    { base: 'outspend', past: 'outspent', participle: 'outspent', meaning: 'chi tiêu nhiều hơn', group: 'pastpart', tier: 'derived', note: 'gốc: spend' },
    { base: 'foretell', past: 'foretold', participle: 'foretold', meaning: 'tiên đoán, báo trước', group: 'pastpart', tier: 'derived', note: 'gốc: tell' },
    { base: 'inbreed', past: 'inbred', participle: 'inbred', meaning: 'giao phối cận huyết', group: 'pastpart', tier: 'extra', note: 'gốc: breed' },
    { base: 'interbreed', past: 'interbred', participle: 'interbred', meaning: 'lai giống', group: 'pastpart', tier: 'extra', note: 'gốc: breed' },
    { base: 'become', past: 'became', participle: 'become', meaning: 'trở nên, trở thành', group: 'basepart', tier: 'core' },
    { base: 'come', past: 'came', participle: 'come', meaning: 'đến', group: 'basepart', tier: 'core' },
    { base: 'run', past: 'ran', participle: 'run', meaning: 'chạy, vận hành, điều hành', group: 'basepart', tier: 'core' },
    { base: 'outrun', past: 'outran', participle: 'outrun', meaning: 'chạy nhanh hơn', group: 'basepart', tier: 'derived', note: 'gốc: run' },
    { base: 'overcome', past: 'overcame', participle: 'overcome', meaning: 'vượt qua, khắc phục', group: 'basepart', tier: 'derived', note: 'gốc: come' },
    { base: 'overrun', past: 'overran', participle: 'overrun', meaning: 'tràn ngập, tràn qua', group: 'basepart', tier: 'derived', note: 'gốc: run' },
    { base: 'rerun', past: 'reran', participle: 'rerun', meaning: 'chạy lại, chiếu lại', group: 'basepart', tier: 'derived', note: 'gốc: run' },
    { base: 'arise', past: 'arose', participle: 'arisen', meaning: 'phát sinh, nảy sinh', group: 'other', tier: 'core' },
    { base: 'awake', past: 'awoke', participle: 'awoken', meaning: 'thức dậy, đánh thức', group: 'other', tier: 'core' },
    { base: 'be', past: 'was/were', participle: 'been', meaning: 'thì, là, ở', group: 'other', tier: 'core' },
    { base: 'bear', past: 'bore', participle: 'borne/born', meaning: 'chịu đựng, mang; sinh ra', group: 'other', tier: 'core' },
    { base: 'beat', past: 'beat', participle: 'beaten', meaning: 'đánh, đập, đánh bại', group: 'other', tier: 'core' },
    { base: 'begin', past: 'began', participle: 'begun', meaning: 'bắt đầu', group: 'other', tier: 'core' },
    { base: 'bite', past: 'bit', participle: 'bitten', meaning: 'cắn', group: 'other', tier: 'core' },
    { base: 'blow', past: 'blew', participle: 'blown', meaning: 'thổi', group: 'other', tier: 'core' },
    { base: 'break', past: 'broke', participle: 'broken', meaning: 'làm vỡ, phá vỡ', group: 'other', tier: 'core' },
    { base: 'choose', past: 'chose', participle: 'chosen', meaning: 'chọn', group: 'other', tier: 'core' },
    { base: 'do', past: 'did', participle: 'done', meaning: 'làm', group: 'other', tier: 'core' },
    { base: 'draw', past: 'drew', participle: 'drawn', meaning: 'vẽ, kéo, rút ra', group: 'other', tier: 'core' },
    { base: 'drink', past: 'drank', participle: 'drunk', meaning: 'uống', group: 'other', tier: 'core' },
    { base: 'drive', past: 'drove', participle: 'driven', meaning: 'lái xe, thúc đẩy', group: 'other', tier: 'core' },
    { base: 'eat', past: 'ate', participle: 'eaten', meaning: 'ăn', group: 'other', tier: 'core' },
    { base: 'fall', past: 'fell', participle: 'fallen', meaning: 'ngã, rơi', group: 'other', tier: 'core' },
    { base: 'fly', past: 'flew', participle: 'flown', meaning: 'bay', group: 'other', tier: 'core' },
    { base: 'forbid', past: 'forbade', participle: 'forbidden', meaning: 'cấm, cấm đoán', group: 'other', tier: 'core' },
    { base: 'forget', past: 'forgot', participle: 'forgotten', meaning: 'quên', group: 'other', tier: 'core' },
    { base: 'forgive', past: 'forgave', participle: 'forgiven', meaning: 'tha thứ', group: 'other', tier: 'core' },
    { base: 'freeze', past: 'froze', participle: 'frozen', meaning: 'đóng băng, đông cứng', group: 'other', tier: 'core' },
    { base: 'get', past: 'got', participle: 'got/gotten', meaning: 'có được, trở nên, nhận', group: 'other', tier: 'core' },
    { base: 'give', past: 'gave', participle: 'given', meaning: 'đưa, cho', group: 'other', tier: 'core' },
    { base: 'go', past: 'went', participle: 'gone', meaning: 'đi', group: 'other', tier: 'core' },
    { base: 'grow', past: 'grew', participle: 'grown', meaning: 'lớn lên, phát triển, trồng', group: 'other', tier: 'core' },
    { base: 'hide', past: 'hid', participle: 'hidden', meaning: 'ẩn, giấu', group: 'other', tier: 'core' },
    { base: 'know', past: 'knew', participle: 'known', meaning: 'biết', group: 'other', tier: 'core' },
    { base: 'lie', past: 'lay', participle: 'lain', meaning: 'nằm (khác với lie-lied-lied: nói dối, động từ có quy tắc)', group: 'other', tier: 'core' },
    { base: 'prove', past: 'proved', participle: 'proven/proved', meaning: 'chứng minh', group: 'other', tier: 'core' },
    { base: 'ride', past: 'rode', participle: 'ridden', meaning: 'cưỡi, đi (xe)', group: 'other', tier: 'core' },
    { base: 'ring', past: 'rang', participle: 'rung', meaning: 'rung chuông, gọi điện', group: 'other', tier: 'core' },
    { base: 'rise', past: 'rose', participle: 'risen', meaning: 'tăng lên, mọc lên, đứng dậy', group: 'other', tier: 'core' },
    { base: 'saw', past: 'sawed', participle: 'sawn/sawed', meaning: 'cưa', group: 'other', tier: 'core' },
    { base: 'see', past: 'saw', participle: 'seen', meaning: 'thấy', group: 'other', tier: 'core' },
    { base: 'sew', past: 'sewed', participle: 'sewn/sewed', meaning: 'may, khâu', group: 'other', tier: 'core' },
    { base: 'shake', past: 'shook', participle: 'shaken', meaning: 'lắc, rung chuyển', group: 'other', tier: 'core' },
    { base: 'show', past: 'showed', participle: 'shown/showed', meaning: 'cho thấy, trình diễn', group: 'other', tier: 'core' },
    { base: 'shrink', past: 'shrank/shrunk', participle: 'shrunk/shrunken', meaning: 'co rút, thu nhỏ', group: 'other', tier: 'core' },
    { base: 'sing', past: 'sang', participle: 'sung', meaning: 'hát', group: 'other', tier: 'core' },
    { base: 'sink', past: 'sank', participle: 'sunk', meaning: 'chìm', group: 'other', tier: 'core' },
    { base: 'speak', past: 'spoke', participle: 'spoken', meaning: 'nói', group: 'other', tier: 'core' },
    { base: 'spring', past: 'sprang/sprung', participle: 'sprung', meaning: 'nhảy vọt, bật lên', group: 'other', tier: 'core' },
    { base: 'steal', past: 'stole', participle: 'stolen', meaning: 'ăn cắp', group: 'other', tier: 'core' },
    { base: 'stink', past: 'stank/stunk', participle: 'stunk', meaning: 'bốc mùi hôi', group: 'other', tier: 'core' },
    { base: 'stride', past: 'strode', participle: 'stridden', meaning: 'bước sải dài', group: 'other', tier: 'extra' },
    { base: 'strive', past: 'strove/strived', participle: 'striven/strived', meaning: 'cố gắng, nỗ lực', group: 'other', tier: 'extra' },
    { base: 'swear', past: 'swore', participle: 'sworn', meaning: 'thề, chửi thề', group: 'other', tier: 'core' },
    { base: 'swell', past: 'swelled', participle: 'swollen/swelled', meaning: 'phồng lên, sưng lên', group: 'other', tier: 'extra' },
    { base: 'swim', past: 'swam', participle: 'swum', meaning: 'bơi', group: 'other', tier: 'core' },
    { base: 'take', past: 'took', participle: 'taken', meaning: 'lấy, mang, dành (thời gian)', group: 'other', tier: 'core' },
    { base: 'tear', past: 'tore', participle: 'torn', meaning: 'xé, rách', group: 'other', tier: 'core' },
    { base: 'throw', past: 'threw', participle: 'thrown', meaning: 'ném', group: 'other', tier: 'core' },
    { base: 'wake', past: 'woke', participle: 'woken', meaning: 'đánh thức, thức dậy', group: 'other', tier: 'core' },
    { base: 'wear', past: 'wore', participle: 'worn', meaning: 'mặc, đeo, mòn dần', group: 'other', tier: 'core' },
    { base: 'weave', past: 'wove/weaved', participle: 'woven/weaved', meaning: 'dệt, đan xen', group: 'other', tier: 'extra' },
    { base: 'write', past: 'wrote', participle: 'written', meaning: 'viết', group: 'other', tier: 'core' },
    { base: 'abide', past: 'abode/abided', participle: 'abode/abided', meaning: 'ở, tuân theo (abide by)', group: 'other', tier: 'extra' },
    { base: 'bespeak', past: 'bespoke', participle: 'bespoken', meaning: 'chứng tỏ, báo trước', group: 'other', tier: 'extra', note: 'gốc: speak' },
    { base: 'cleave', past: 'cleft/clove/cleaved', participle: 'cleft/cloven/cleaved', meaning: 'chẻ, tách ra', group: 'other', tier: 'extra' },
    { base: 'dwell', past: 'dwelt/dwelled', participle: 'dwelt/dwelled', meaning: 'cư trú, trú ngụ', group: 'pastpart', tier: 'extra' },
    { base: 'forbear', past: 'forbore', participle: 'forborne', meaning: 'nhịn, kiềm chế', group: 'other', tier: 'extra', note: 'gốc: bear' },
    { base: 'forgo', past: 'forwent', participle: 'forgone', meaning: 'từ bỏ, bỏ qua', group: 'other', tier: 'extra', note: 'gốc: go' },
    { base: 'forsake', past: 'forsook', participle: 'forsaken', meaning: 'ruồng bỏ, từ bỏ', group: 'other', tier: 'extra' },
    { base: 'heave', past: 'heaved/hove', participle: 'heaved/hove', meaning: 'nâng lên, kéo mạnh', group: 'other', tier: 'extra' },
    { base: 'hew', past: 'hewed', participle: 'hewn/hewed', meaning: 'chặt, đốn', group: 'other', tier: 'extra' },
    { base: 'mow', past: 'mowed', participle: 'mown/mowed', meaning: 'cắt (cỏ)', group: 'other', tier: 'extra' },
    { base: 'rend', past: 'rent', participle: 'rent', meaning: 'xé toạc', group: 'pastpart', tier: 'extra' },
    { base: 'shear', past: 'sheared', participle: 'shorn/sheared', meaning: 'xén lông (cừu)', group: 'other', tier: 'extra' },
    { base: 'slay', past: 'slew', participle: 'slain', meaning: 'giết hại, hạ gục', group: 'other', tier: 'extra' },
    { base: 'smite', past: 'smote', participle: 'smitten', meaning: 'đánh mạnh, trừng phạt', group: 'other', tier: 'extra' },
    { base: 'sow', past: 'sowed', participle: 'sown/sowed', meaning: 'gieo (hạt)', group: 'other', tier: 'extra' },
    { base: 'spit', past: 'spat/spit', participle: 'spat/spit', meaning: 'nhổ (nước bọt)', group: 'other', tier: 'extra' },
    { base: 'thrive', past: 'thrived/throve', participle: 'thrived/thriven', meaning: 'phát triển mạnh, thịnh vượng', group: 'other', tier: 'extra' },
    { base: 'tread', past: 'trod', participle: 'trodden/trod', meaning: 'giẫm, đạp lên', group: 'other', tier: 'extra' },
    { base: 'wed', past: 'wed/wedded', participle: 'wed/wedded', meaning: 'kết hôn, cưới', group: 'same', tier: 'extra' },
    { base: 'foresee', past: 'foresaw', participle: 'foreseen', meaning: 'thấy trước, tiên đoán', group: 'other', tier: 'derived', note: 'gốc: see' },
    { base: 'misspeak', past: 'misspoke', participle: 'misspoken', meaning: 'nói sai, lỡ lời', group: 'other', tier: 'derived', note: 'gốc: speak' },
    { base: 'mistake', past: 'mistook', participle: 'mistaken', meaning: 'nhầm lẫn', group: 'other', tier: 'derived', note: 'gốc: take' },
    { base: 'outdo', past: 'outdid', participle: 'outdone', meaning: 'vượt trội, làm giỏi hơn', group: 'other', tier: 'derived', note: 'gốc: do' },
    { base: 'outgrow', past: 'outgrew', participle: 'outgrown', meaning: 'lớn nhanh hơn, lớn vượt khỏi', group: 'other', tier: 'derived', note: 'gốc: grow' },
    { base: 'overdo', past: 'overdid', participle: 'overdone', meaning: 'làm quá mức, nấu quá lửa', group: 'other', tier: 'derived', note: 'gốc: do' },
    { base: 'overdraw', past: 'overdrew', participle: 'overdrawn', meaning: 'rút quá số dư', group: 'other', tier: 'derived', note: 'gốc: draw' },
    { base: 'overeat', past: 'overate', participle: 'overeaten', meaning: 'ăn quá nhiều', group: 'other', tier: 'derived', note: 'gốc: eat' },
    { base: 'override', past: 'overrode', participle: 'overridden', meaning: 'ghi đè, bác bỏ (quyết định)', group: 'other', tier: 'derived', note: 'gốc: ride' },
    { base: 'oversee', past: 'oversaw', participle: 'overseen', meaning: 'giám sát, trông coi', group: 'other', tier: 'derived', note: 'gốc: see' },
    { base: 'overtake', past: 'overtook', participle: 'overtaken', meaning: 'vượt qua, bắt kịp', group: 'other', tier: 'derived', note: 'gốc: take' },
    { base: 'overthrow', past: 'overthrew', participle: 'overthrown', meaning: 'lật đổ', group: 'other', tier: 'derived', note: 'gốc: throw' },
    { base: 'partake', past: 'partook', participle: 'partaken', meaning: 'tham gia, dự phần', group: 'other', tier: 'derived', note: 'gốc: take' },
    { base: 'redo', past: 'redid', participle: 'redone', meaning: 'làm lại', group: 'other', tier: 'derived', note: 'gốc: do' },
    { base: 'redraw', past: 'redrew', participle: 'redrawn', meaning: 'vẽ lại, kéo lại', group: 'other', tier: 'derived', note: 'gốc: draw' },
    { base: 'regrow', past: 'regrew', participle: 'regrown', meaning: 'mọc lại, trồng lại', group: 'other', tier: 'derived', note: 'gốc: grow' },
    { base: 'retake', past: 'retook', participle: 'retaken', meaning: 'lấy lại, thi/quay lại', group: 'other', tier: 'derived', note: 'gốc: take' },
    { base: 'rewrite', past: 'rewrote', participle: 'rewritten', meaning: 'viết lại', group: 'other', tier: 'derived', note: 'gốc: write' },
    { base: 'overwrite', past: 'overwrote', participle: 'overwritten', meaning: 'ghi đè lên (dữ liệu)', group: 'other', tier: 'derived', note: 'gốc: write' },
    { base: 'underwrite', past: 'underwrote', participle: 'underwritten', meaning: 'bảo lãnh, bảo hiểm cho', group: 'other', tier: 'derived', note: 'gốc: write' },
    { base: 'undergo', past: 'underwent', participle: 'undergone', meaning: 'trải qua', group: 'other', tier: 'derived', note: 'gốc: go' },
    { base: 'underlie', past: 'underlay', participle: 'underlain', meaning: 'là nền tảng của, nằm bên dưới', group: 'other', tier: 'derived', note: 'gốc: lie' },
    { base: 'undertake', past: 'undertook', participle: 'undertaken', meaning: 'đảm nhận, tiến hành', group: 'other', tier: 'derived', note: 'gốc: take' },
    { base: 'withdraw', past: 'withdrew', participle: 'withdrawn', meaning: 'rút lui, rút (tiền)', group: 'other', tier: 'derived', note: 'gốc: draw' },
];

